use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use std::{
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
};

pub const MODEL_TASK: &str = "zedAndroidJavaModel";
const OUTPUT_PREFIX: &str = "ANDROID_IDE_JAVA_MODEL=";
const CACHE_MARKER: &str = "# Generated by Android IDE for Java language support.\n*\n";

// AGP 9 removed the legacy variant model used by JDT LS. Export the actual compile
// graph, then let Buildship consume its normal Eclipse model without editing builds.
const EXPORT_INIT: &str = r#"def androidCompilations = [:]
gradle.beforeProject { project ->
    ['com.android.application', 'com.android.library'].each { plugin ->
        project.plugins.withId(plugin) {
            def components = project.extensions.getByName('androidComponents')
            components.onVariants(components.selector().all(), { variant ->
                def compileName = 'compile' + variant.name.substring(0, 1).toUpperCase(java.util.Locale.ROOT) + variant.name.substring(1) + 'JavaWithJavac'
                def compilePath = (project.path == ':' ? ':' : project.path + ':') + compileName
                androidCompilations[compilePath] = [variant: variant.name, sources: variant.sources.java?.all]
            } as org.gradle.api.Action)
        }
    }
}
gradle.projectsEvaluated {
    gradle.rootProject.tasks.register('zedAndroidJavaModel') {
        dependsOn(System.getProperty('zed.android.compileTask'))
        doLast {
            def models = gradle.taskGraph.allTasks.findAll { androidCompilations.containsKey(it.path) }.collect { compile ->
                def compilation = androidCompilations[compile.path]
                def sources = compilation.sources?.get()?.collect { it.asFile } ?: []
                def libraries = compile.classpath.files + (compile.options.bootstrapClasspath?.files ?: [])
                [project: compile.project.path, variant: compilation.variant, directory: compile.project.projectDir.absolutePath,
                 sourceCompatibility: compile.sourceCompatibility, targetCompatibility: compile.targetCompatibility,
                 sources: sources.findAll { it.isDirectory() }*.absolutePath,
                 libraries: libraries.findAll { it.exists() }.unique()*.absolutePath]
            }
            println('ANDROID_IDE_JAVA_MODEL=' + groovy.json.JsonOutput.toJson(models))
        }
    }
}
"#;
const IMPORT_INIT: &str = r#"import org.gradle.plugins.ide.eclipse.model.Library
import org.gradle.plugins.ide.eclipse.model.SourceFolder
import org.gradle.plugins.ide.eclipse.model.internal.FileReferenceFactory

def models = new groovy.json.JsonSlurper().parse(new File(System.getProperty('zed.android.javaModel')))
gradle.beforeProject { project ->
    def model = models.find { it.project == project.path && new File(it.directory) == project.projectDir }
    if (model == null) return
    project.pluginManager.apply('eclipse')
    project.afterEvaluate {
        def eclipse = project.extensions.getByName('eclipse')
        eclipse.project.natures('org.eclipse.jdt.core.javanature')
        eclipse.project.buildCommand('org.eclipse.jdt.core.javabuilder')
        eclipse.classpath.defaultOutputDir = project.file('build/android-ide/jdt')
        eclipse.jdt.sourceCompatibility = model.sourceCompatibility
        eclipse.jdt.targetCompatibility = model.targetCompatibility
        eclipse.classpath.file.whenMerged { classpath ->
            classpath.entries.removeAll { it.kind in ['src', 'lib'] }
            model.sources.each { directory ->
                classpath.entries.add(new SourceFolder(project.relativePath(directory), 'build/android-ide/jdt'))
            }
            def references = new FileReferenceFactory()
            model.libraries.each { file ->
                classpath.entries.add(new Library(references.fromFile(new File(file))))
            }
        }
    }
}
"#;

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JavaModule {
    pub project: String,
    pub variant: String,
    pub directory: PathBuf,
    pub source_compatibility: String,
    pub target_compatibility: String,
    pub sources: Vec<PathBuf>,
    pub libraries: Vec<PathBuf>,
}

pub fn is_configured(root: &Path) -> bool {
    let cache = root.join(".zed/android-java");
    fs::read_to_string(cache.join(".gitignore")).is_ok_and(|marker| marker == CACHE_MARKER)
        && cache.join("model.json").is_file()
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    let settings = root.join(".zed");
    ensure_directory(&settings)?;
    let cache = settings.join("android-java");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
            "The .zed/android-java directory contains unmanaged files. Move it aside before configuring Java."
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), CACHE_MARKER, false)?;
    }
    let export = cache.join("export.gradle");
    atomic_write(&export, EXPORT_INIT, false)?;
    atomic_write(&cache.join("import.gradle"), IMPORT_INIT, false)?;
    Ok(export)
}

pub fn parse_model(output: &str, root: &Path, target: &AndroidTarget) -> Result<Vec<JavaModule>> {
    let mut records = output
        .lines()
        .filter_map(|line| line.strip_prefix(OUTPUT_PREFIX));
    let record = records
        .next()
        .context("Gradle did not return an Android Java model")?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Android Java models"
    );
    let models: Vec<JavaModule> =
        serde_json::from_str(record).context("Invalid Android Java model")?;
    let root = root.canonicalize()?;
    let mut projects = HashSet::new();
    for model in &models {
        ensure!(
            projects.insert(&model.project),
            "Multiple Java variants selected for {}",
            model.project
        );
        ensure!(
            model.directory.is_absolute() && model.directory.canonicalize()?.starts_with(&root),
            "Java module {} is outside the selected project",
            model.project
        );
        for path in &model.sources {
            ensure!(
                path.is_absolute() && path.is_dir() && path.canonicalize()?.starts_with(&root),
                "Java source directory is missing or outside the selected project: {}",
                path.display()
            );
        }
        ensure!(
            !model.libraries.is_empty(),
            "Java classpath is empty for {}",
            model.project
        );
        for path in &model.libraries {
            ensure!(
                path.is_absolute() && (path.is_file() || path.is_dir()),
                "Java classpath entry is missing: {}",
                path.display()
            );
        }
    }
    ensure!(
        models
            .iter()
            .any(|model| model.project == target.module && model.variant == target.variant),
        "Java model does not contain the selected Android variant"
    );
    Ok(models)
}

pub fn install_model(root: &Path, models: &[JavaModule]) -> Result<PathBuf> {
    let cache = root.join(".zed/android-java");
    ensure_directory(&root.join(".zed"))?;
    ensure_directory(&cache)?;
    ensure!(
        fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
        "Prepare the Java cache before installing its model"
    );
    let path = cache.join("model.json");
    atomic_write(&path, &serde_json::to_string_pretty(models)?, false)?;
    Ok(path)
}

pub fn finish(root: &Path, models: &[JavaModule], previous: &str, updated: &str) -> Result<()> {
    ensure!(
        crate::kotlin::read_settings(root)? == previous,
        "Project settings changed during Java setup. Retry to preserve your latest edits."
    );
    install_model(root, models)?;
    atomic_write(&root.join(".zed/settings.json"), updated, false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn java_model_preserves_user_files_and_validates_selected_variant() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let module = root.join("mobile");
        let source = module.join("src/main/java");
        fs::create_dir_all(&source)?;
        let library = root.join("android sdk.jar");
        fs::write(&library, "test")?;
        let target = AndroidTarget {
            module: ":mobile".into(),
            variant: "fullDebug".into(),
            output_listing: root.join("output.json"),
        };
        let mut models = vec![JavaModule {
            project: target.module.clone(),
            variant: target.variant.clone(),
            directory: module,
            source_compatibility: "11".into(),
            target_compatibility: "11".into(),
            sources: vec![source],
            libraries: vec![library],
        }];
        let output = format!(
            "noise\n{OUTPUT_PREFIX}{}\n",
            serde_json::to_string(&models)?
        );
        assert_eq!(parse_model(&output, &root, &target)?.len(), 1);
        assert!(parse_model(&(output.clone() + &output), &root, &target).is_err());
        models[0].variant = "demoDebug".into();
        assert!(
            parse_model(
                &format!("{OUTPUT_PREFIX}{}", serde_json::to_string(&models)?),
                &root,
                &target
            )
            .is_err()
        );
        models[0].variant = target.variant.clone();
        models[0].sources.push(temporary.path().join("missing"));
        assert!(
            parse_model(
                &format!("{OUTPUT_PREFIX}{}", serde_json::to_string(&models)?),
                &root,
                &target
            )
            .is_err()
        );
        let cache = root.join(".zed/android-java");
        assert!(!is_configured(&root));
        fs::create_dir_all(&cache)?;
        fs::write(cache.join(".gitignore"), "user files")?;
        assert!(prepare(&root).is_err());
        assert_eq!(fs::read_to_string(cache.join(".gitignore"))?, "user files");
        fs::rename(&cache, root.join("user-java-cache"))?;
        assert!(prepare(&root)?.is_file());
        let parsed = parse_model(&output, &root, &target)?;
        assert!(install_model(&root, &parsed)?.is_file());
        assert!(is_configured(&root));
        assert!(prepare(&root)?.is_file());
        finish(&root, &parsed, "{}\n", "{\"tab_size\":2}")?;
        assert!(finish(&root, &parsed, "{}\n", "{\"tab_size\":4}").is_err());
        assert_eq!(crate::kotlin::read_settings(&root)?, "{\"tab_size\":2}");
        #[cfg(unix)]
        {
            fs::rename(&cache, root.join("generated-cache"))?;
            std::os::unix::fs::symlink(root.join("generated-cache"), &cache)?;
            assert!(prepare(&root).is_err());
            assert!(install_model(&root, &parsed).is_err());
        }
        Ok(())
    }
}
