use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use std::{
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
};

pub const MODEL_TASK: &str = "zedAndroidJavaModel";
const OUTPUT_PREFIX: &str = "ANDROID_IDE_JAVA_MODEL=";
const CACHE_MARKER: &str = "# Generated by Android IDE for Java language support.\n*\n";

// AGP 9 removed the legacy variant model used by JDT LS. Export the actual compile
// graph, then let Buildship consume its normal Eclipse model without editing builds.
const EXPORT_INIT: &str = r#"def selection = new groovy.json.JsonSlurper().parse(new File(System.getProperty('koda.android.selection')))
gradle.projectsEvaluated {
    def compilations = selection.collectMany { model ->
        def project = gradle.rootProject.project(model.project)
        if (project.projectDir.canonicalPath != new File(model.directory).canonicalPath) throw new GradleException('Android module directory changed; sync again: ' + model.project)
        model.components.collect { component ->
            def name = model.kind == 'jvm' ? (component.scope == 'main' ? 'compileJava' : 'compileTestJava') :
                'compile' + component.name.substring(0, 1).toUpperCase(java.util.Locale.ROOT) + component.name.substring(1) + 'JavaWithJavac'
            [model: model, component: component, task: project.tasks.named(name)]
        }
    }
    gradle.rootProject.tasks.register('zedAndroidJavaModel') {
        dependsOn(compilations.collect { it.task })
        doLast {
            def models = selection.collect { model ->
                def entries = compilations.findAll { it.model.project == model.project }
                def main = entries.find { it.component.scope == 'main' }.task.get()
                def libraries = { entriesToExport -> entriesToExport.collectMany { entry ->
                    def compile = entry.task.get()
                    (compile.classpath.files + (compile.options.bootstrapClasspath?.files ?: [])).findAll { it.exists() }*.absolutePath
                }.unique() }
                def roots = { scope -> entries.findAll { (it.component.scope != 'main') == scope }.collectMany { entry ->
                    entry.component.sources.findAll { it.kind in ['java', 'kotlin'] }.collect { new File(it.path) }.findAll { it.isDirectory() }*.absolutePath
                }.unique() }
                [project: model.project, variant: model.variant, directory: model.directory,
                 sourceCompatibility: main.sourceCompatibility, targetCompatibility: main.targetCompatibility,
                 sources: roots(false), testSources: roots(true),
                 libraries: libraries(entries.findAll { it.component.scope == 'main' }),
                 testLibraries: libraries(entries.findAll { it.component.scope != 'main' })]
            }
            println('ANDROID_IDE_JAVA_MODEL=' + groovy.json.JsonOutput.toJson(models))
        }
    }
}
"#;
const IMPORT_INIT: &str = r#"import org.gradle.plugins.ide.eclipse.model.Library
import org.gradle.plugins.ide.eclipse.model.SourceFolder
import org.gradle.plugins.ide.eclipse.model.internal.FileReferenceFactory

def models = new groovy.json.JsonSlurper().parse(new File(System.getProperty('zed.android.javaModel')))
gradle.beforeProject { project ->
    def model = models.find { it.project == project.path && new File(it.directory) == project.projectDir }
    if (model == null) return
    project.pluginManager.apply('eclipse')
    project.afterEvaluate {
        def eclipse = project.extensions.getByName('eclipse')
        eclipse.project.natures('org.eclipse.jdt.core.javanature')
        eclipse.project.buildCommand('org.eclipse.jdt.core.javabuilder')
        eclipse.classpath.defaultOutputDir = project.file('build/android-ide/jdt')
        eclipse.jdt.sourceCompatibility = model.sourceCompatibility
        eclipse.jdt.targetCompatibility = model.targetCompatibility
        eclipse.classpath.file.whenMerged { classpath ->
            classpath.entries.removeAll { it.kind in ['src', 'lib'] }
            model.sources.each { directory ->
                classpath.entries.add(new SourceFolder(project.relativePath(directory), 'build/android-ide/jdt'))
            }
            (model.testSources ?: []).findAll { !model.sources.contains(it) }.each { directory ->
                def source = new SourceFolder(project.relativePath(directory), 'build/android-ide/jdt-test')
                source.entryAttributes['test'] = 'true'
                classpath.entries.add(source)
            }
            def references = new FileReferenceFactory()
            model.libraries.each { file ->
                classpath.entries.add(new Library(references.fromFile(new File(file))))
            }
            (model.testLibraries ?: []).findAll { !model.libraries.contains(it) }.each { file ->
                def library = new Library(references.fromFile(new File(file)))
                library.entryAttributes['test'] = 'true'
                classpath.entries.add(library)
            }
        }
    }
}
"#;

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct JavaModule {
    pub project: String,
    pub variant: String,
    pub directory: PathBuf,
    pub source_compatibility: String,
    pub target_compatibility: String,
    pub sources: Vec<PathBuf>,
    pub libraries: Vec<PathBuf>,
    #[serde(default)]
    pub test_sources: Vec<PathBuf>,
    #[serde(default)]
    pub test_libraries: Vec<PathBuf>,
}

pub fn is_configured(root: &Path) -> bool {
    let cache = root.join(".koda/android-java");
    fs::read_to_string(cache.join(".gitignore")).is_ok_and(|marker| marker == CACHE_MARKER)
        && cache.join("model.json").is_file()
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    let settings = root.join(".koda");
    ensure_directory(&settings)?;
    let cache = settings.join("android-java");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
            "The .koda/android-java directory contains unmanaged files. Move it aside before configuring Java."
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), CACHE_MARKER, false)?;
    }
    let export = cache.join("export.gradle");
    atomic_write(&export, EXPORT_INIT, false)?;
    atomic_write(&cache.join("import.gradle"), IMPORT_INIT, false)?;
    Ok(export)
}

pub fn prepare_selected(
    root: &Path,
    selected: &crate::project_model::SelectedProject,
) -> Result<(PathBuf, PathBuf)> {
    let export = prepare(root)?;
    ensure!(
        selected.model.root == root.canonicalize()?,
        "The Java selection belongs to a different project"
    );
    let models = selected.projection();
    let selection = root.join(".koda/android-java/selection.json");
    atomic_write(&selection, &serde_json::to_string(&models)?, false)?;
    Ok((export, selection))
}

pub fn validate_selection(
    models: &[JavaModule],
    selected: &crate::project_model::SelectedProject,
) -> Result<()> {
    ensure!(
        models.len() == selected.variants.len(),
        "Java import returned an incomplete selected module graph"
    );
    for model in models {
        ensure!(
            selected.variants.get(&model.project) == Some(&model.variant),
            "Java import returned an outdated module variant: {}",
            model.project
        );
        let (module, variant) = selected
            .model
            .variant(&crate::project_model::VariantId {
                module: model.project.clone(),
                variant: model.variant.clone(),
            })
            .context("Java module is absent from the selected graph")?;
        ensure!(
            model.directory == module.directory,
            "Java module directory changed during import"
        );
        for (paths, test) in [(&model.sources, false), (&model.test_sources, true)] {
            for path in paths {
                ensure!(
                    variant
                        .components
                        .iter()
                        .filter(|component| (component.scope
                            != crate::project_model::SourceScope::Main)
                            == test)
                        .flat_map(|component| &component.sources)
                        .any(|source| source.path == *path
                            && matches!(
                                source.kind,
                                crate::project_model::SourceKind::Java
                                    | crate::project_model::SourceKind::Kotlin
                            )),
                    "Java source is not part of the selected component: {}",
                    path.display()
                );
            }
        }
    }
    Ok(())
}

pub fn parse_model(output: &str, root: &Path, target: &AndroidTarget) -> Result<Vec<JavaModule>> {
    let mut records = output
        .lines()
        .filter_map(|line| line.strip_prefix(OUTPUT_PREFIX));
    let record = records
        .next()
        .context("Gradle did not return an Android Java model")?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Android Java models"
    );
    let models: Vec<JavaModule> =
        serde_json::from_str(record).context("Invalid Android Java model")?;
    let root = root.canonicalize()?;
    let mut projects = HashSet::new();
    for model in &models {
        ensure!(
            projects.insert(&model.project),
            "Multiple Java variants selected for {}",
            model.project
        );
        ensure!(
            model.directory.is_absolute() && model.directory.canonicalize()?.starts_with(&root),
            "Java module {} is outside the selected project",
            model.project
        );
        for path in model.sources.iter().chain(&model.test_sources) {
            ensure!(
                path.is_absolute() && path.is_dir() && path.canonicalize()?.starts_with(&root),
                "Java source directory is missing or outside the selected project: {}",
                path.display()
            );
        }
        ensure!(
            model.project != target.module || !model.libraries.is_empty(),
            "Java classpath is empty for {}",
            model.project
        );
        for path in model.libraries.iter().chain(&model.test_libraries) {
            ensure!(
                path.is_absolute() && (path.is_file() || path.is_dir()),
                "Java classpath entry is missing: {}",
                path.display()
            );
        }
    }
    ensure!(
        models
            .iter()
            .any(|model| model.project == target.module && model.variant == target.variant),
        "Java model does not contain the selected Android variant"
    );
    Ok(models)
}

pub fn install_model(root: &Path, models: &[JavaModule]) -> Result<PathBuf> {
    let cache = root.join(".koda/android-java");
    ensure_directory(&root.join(".koda"))?;
    ensure_directory(&cache)?;
    ensure!(
        fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
        "Prepare the Java cache before installing its model"
    );
    let path = cache.join("model.json");
    atomic_write(&path, &serde_json::to_string_pretty(models)?, false)?;
    Ok(path)
}

pub fn finish(root: &Path, models: &[JavaModule], previous: &str, updated: &str) -> Result<()> {
    ensure!(
        crate::kotlin::read_settings(root)? == previous,
        "Project settings changed during Java setup. Retry to preserve your latest edits."
    );
    install_model(root, models)?;
    atomic_write(&root.join(".koda/settings.json"), updated, false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn java_model_preserves_user_files_and_validates_selected_variant() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let module = root.join("mobile");
        let source = module.join("src/main/java");
        fs::create_dir_all(&source)?;
        let library = root.join("android sdk.jar");
        fs::write(&library, "test")?;
        let target = AndroidTarget {
            module: ":mobile".into(),
            variant: "fullDebug".into(),
            output_listing: root.join("output.json"),
        };
        let mut models = vec![JavaModule {
            project: target.module.clone(),
            variant: target.variant.clone(),
            directory: module,
            source_compatibility: "11".into(),
            target_compatibility: "11".into(),
            test_sources: Vec::new(),
            test_libraries: Vec::new(),
            sources: vec![source],
            libraries: vec![library],
        }];
        let output = format!(
            "noise\n{OUTPUT_PREFIX}{}\n",
            serde_json::to_string(&models)?
        );
        assert_eq!(parse_model(&output, &root, &target)?.len(), 1);
        assert!(parse_model(&(output.clone() + &output), &root, &target).is_err());
        models[0].variant = "demoDebug".into();
        assert!(
            parse_model(
                &format!("{OUTPUT_PREFIX}{}", serde_json::to_string(&models)?),
                &root,
                &target
            )
            .is_err()
        );
        models[0].variant = target.variant.clone();
        models[0].sources.push(temporary.path().join("missing"));
        assert!(
            parse_model(
                &format!("{OUTPUT_PREFIX}{}", serde_json::to_string(&models)?),
                &root,
                &target
            )
            .is_err()
        );
        let cache = root.join(".koda/android-java");
        assert!(!is_configured(&root));
        fs::create_dir_all(&cache)?;
        fs::write(cache.join(".gitignore"), "user files")?;
        assert!(prepare(&root).is_err());
        assert_eq!(fs::read_to_string(cache.join(".gitignore"))?, "user files");
        fs::rename(&cache, root.join("user-java-cache"))?;
        assert!(prepare(&root)?.is_file());
        let parsed = parse_model(&output, &root, &target)?;
        assert!(install_model(&root, &parsed)?.is_file());
        assert!(is_configured(&root));
        assert!(prepare(&root)?.is_file());
        finish(&root, &parsed, "{}\n", "{\"tab_size\":2}")?;
        assert!(finish(&root, &parsed, "{}\n", "{\"tab_size\":4}").is_err());
        assert_eq!(crate::kotlin::read_settings(&root)?, "{\"tab_size\":2}");
        #[cfg(unix)]
        {
            fs::rename(&cache, root.join("generated-cache"))?;
            std::os::unix::fs::symlink(root.join("generated-cache"), &cache)?;
            assert!(prepare(&root).is_err());
            assert!(install_model(&root, &parsed).is_err());
        }
        Ok(())
    }
}
