use anyhow::{Context as _, Result, bail, ensure};
use std::{
    env, fs,
    io::Write,
    path::{Path, PathBuf},
};

pub const CLASSPATH_TASK: &str = "zedAndroidKotlinClasspath";
const OUTPUT_PREFIX: &str = "ZED_ANDROID_KOTLIN_CLASSPATH=";
const SOURCES_PREFIX: &str = "ZED_ANDROID_KOTLIN_SOURCES=";
const CACHE_MARKER: &str = "# Generated by Android IDE for Kotlin language support.\n*\n";
const UNIX_HOOK: &str = "#!/bin/sh\n# Generated by Android IDE for Kotlin language support.\ncat \"$(dirname \"$0\")/.zed/android-kotlin/classpath.txt\"\n";
const WINDOWS_HOOK: &str = "@echo off\r\nrem Generated by Android IDE for Kotlin language support.\r\ntype \"%~dp0.zed\\android-kotlin\\classpath.txt\"\r\n";

// ponytail: one selected variant supplies the workspace classpath; replace with a per-module
// project model when mixed-variant or multiplatform editing is required.
const GRADLE_INIT: &str = r#"gradle.projectsEvaluated {
    allprojects { project ->
        def compile = project.tasks.findByName(System.getProperty('zed.android.compileTask'))
        if (compile != null && compile.hasProperty('libraries')) {
            def javaCompile = project.tasks.findByName(compile.name.replaceFirst(/Kotlin$/, 'JavaWithJavac'))
            def javaClasses = javaCompile == null ? project.files() :
                project.files(javaCompile.destinationDirectory).filter { it.isDirectory() }
            def variant = compile.name.replaceFirst(/^compile/, '').replaceFirst(/Kotlin$/, '')
            variant = variant.substring(0, 1).toLowerCase(java.util.Locale.ROOT) + variant.substring(1)
            def configuration = project.configurations.findByName(variant + 'CompileClasspath')
            def sources = []
            if (configuration != null) {
                def components = configuration.incoming.resolutionResult.allComponents.collect { it.id }
                    .findAll { it instanceof org.gradle.api.artifacts.component.ModuleComponentIdentifier }
                def result = project.dependencies.createArtifactResolutionQuery().forComponents(components)
                    .withArtifacts(org.gradle.jvm.JvmLibrary, org.gradle.language.base.artifact.SourcesArtifact).execute()
                sources = result.resolvedComponents.collectMany { component ->
                    component.getArtifacts(org.gradle.language.base.artifact.SourcesArtifact)
                        .findAll { it instanceof org.gradle.api.artifacts.result.ResolvedArtifactResult }
                        .collect { it.file.absolutePath }
                }.unique().sort()
            }
            project.tasks.register('zedAndroidKotlinClasspath') {
                dependsOn(compile)
                if (javaCompile != null) { dependsOn(javaCompile) }
                // BuildConfig and other generated Java symbols are absent from compile.libraries.
                inputs.files(compile.libraries, javaClasses)
                inputs.property('androidSourceArchives', sources)
                doLast { task ->
                    println('ZED_ANDROID_KOTLIN_CLASSPATH=' + groovy.json.JsonOutput.toJson(
                        task.inputs.files.files.collect { it.absolutePath }))
                    println('ZED_ANDROID_KOTLIN_SOURCES=' + groovy.json.JsonOutput.toJson(
                        task.inputs.properties.androidSourceArchives))
                }
            }
        }
    }
}
"#;

pub fn prepare(root: &Path) -> Result<PathBuf> {
    validate_hooks(root)?;
    let root = root.canonicalize()?;
    let settings = root.join(".zed");
    ensure_directory(&settings)?;
    let cache = settings.join("android-kotlin");
    if cache.exists() {
        ensure!(
            !fs::symlink_metadata(&cache)?.file_type().is_symlink(),
            "Kotlin cache must not be a symlink"
        );
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
            "The .zed/android-kotlin directory already contains unmanaged files. Move it aside before configuring Kotlin."
        );
    } else {
        fs::create_dir(&cache)?;
        atomic_write(&cache.join(".gitignore"), CACHE_MARKER, false)?;
    }
    let init = cache.join("classpath.gradle");
    atomic_write(&init, GRADLE_INIT, false)?;
    Ok(init)
}

fn ensure_directory(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => ensure!(
            metadata.is_dir() && !metadata.file_type().is_symlink(),
            "{} must be a regular directory",
            path.display()
        ),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir(path)?,
        Err(error) => return Err(error.into()),
    }
    Ok(())
}

fn hook() -> (&'static str, &'static str) {
    if cfg!(windows) {
        ("kls-classpath.bat", WINDOWS_HOOK)
    } else {
        ("kls-classpath.sh", UNIX_HOOK)
    }
}

fn validate_hooks(root: &Path) -> Result<()> {
    let (name, expected) = hook();
    for candidate in [
        "kls-classpath",
        "kls-classpath.sh",
        "kls-classpath.bat",
        "kls-classpath.cmd",
    ] {
        let path = root.join(candidate);
        match fs::symlink_metadata(&path) {
            Ok(metadata) => ensure!(
                candidate == name
                    && metadata.is_file()
                    && !metadata.file_type().is_symlink()
                    && fs::read_to_string(&path)? == expected,
                "{} is an existing Kotlin classpath hook. It has been preserved; move it aside before using automatic setup.",
                path.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}

pub fn parse_classpath(output: &str) -> Result<Vec<PathBuf>> {
    let paths = parse_paths(output, OUTPUT_PREFIX)?;
    ensure!(
        !paths.is_empty(),
        "The Kotlin compilation classpath is empty"
    );
    Ok(paths)
}

pub fn parse_sources(output: &str) -> Result<Vec<PathBuf>> {
    let paths = parse_paths(output, SOURCES_PREFIX)?;
    ensure!(
        paths.iter().all(|path| path.is_file()),
        "A Kotlin source archive is missing"
    );
    Ok(paths)
}

fn parse_paths(output: &str, prefix: &str) -> Result<Vec<PathBuf>> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(prefix));
    let record = records.next().context("Gradle did not return a Kotlin compilation classpath. This variant must have a Kotlin compile task.")?;
    ensure!(
        records.next().is_none(),
        "Gradle returned more than one Kotlin classpath"
    );
    let mut paths: Vec<PathBuf> =
        serde_json::from_str(record).context("Invalid Kotlin classpath output")?;
    for path in &paths {
        ensure!(
            path.is_absolute() && (path.is_file() || path.is_dir()),
            "Kotlin classpath entry is missing or not absolute: {}",
            path.display()
        );
        let text = path
            .to_str()
            .context("Kotlin classpath contains a non-Unicode path")?;
        let separator = if cfg!(windows) { ';' } else { ':' };
        ensure!(
            !text.contains(['\n', '\r', separator]),
            "Kotlin classpath contains an unsupported separator: {}",
            path.display()
        );
    }
    paths.sort();
    paths.dedup();
    Ok(paths)
}

pub fn install_classpath(root: &Path, paths: &[PathBuf]) -> Result<()> {
    ensure!(!paths.is_empty(), "The Kotlin classpath is empty");
    validate_hooks(root)?;
    let separator = if cfg!(windows) { ";" } else { ":" };
    let classpath = paths
        .iter()
        .map(|path| path.to_str().context("Non-Unicode Kotlin classpath"))
        .collect::<Result<Vec<_>>>()?
        .join(separator);
    let cache = root.join(".zed/android-kotlin");
    ensure!(
        fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
        "Prepare the Kotlin cache before installing its classpath"
    );
    atomic_write(&cache.join("classpath.txt"), &(classpath + "\n"), false)?;
    let (name, content) = hook();
    atomic_write(&root.join(name), content, true)
}

pub fn read_settings(root: &Path) -> Result<String> {
    let path = root.join(".zed/settings.json");
    match fs::symlink_metadata(&path) {
        Ok(metadata) => {
            ensure!(
                metadata.is_file() && !metadata.file_type().is_symlink(),
                "Project settings must be a regular file for automatic Kotlin setup"
            );
            fs::read_to_string(path).context("Could not read project settings")
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok("{}\n".into()),
        Err(error) => Err(error.into()),
    }
}

pub fn finish(
    root: &Path,
    paths: &[PathBuf],
    previous_settings: &str,
    updated_settings: &str,
) -> Result<()> {
    ensure!(
        read_settings(root)? == previous_settings,
        "Project settings changed during Kotlin setup. Retry to preserve your latest edits."
    );
    install_classpath(root, paths)?;
    atomic_write(&root.join(".zed/settings.json"), updated_settings, false)
}

fn atomic_write(path: &Path, text: &str, executable: bool) -> Result<()> {
    let parent = path
        .parent()
        .context("Generated file has no parent directory")?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(text.as_bytes())?;
    #[cfg(unix)]
    if executable {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(0o755))?;
    }
    #[cfg(not(unix))]
    let _executable = executable;
    temporary
        .persist(path)
        .with_context(|| format!("Could not write {}", path.display()))?;
    Ok(())
}

pub fn java_home() -> Result<PathBuf> {
    if let Some(path) = env::var_os("ANDROID_IDE_KOTLIN_JAVA_HOME") {
        let path = PathBuf::from(path);
        ensure!(
            is_java_21(&path),
            "ANDROID_IDE_KOTLIN_JAVA_HOME must point to JDK 21"
        );
        return Ok(path);
    }
    if let Some(path) = env::var_os("JAVA_HOME").map(PathBuf::from)
        && is_java_21(&path)
    {
        return Ok(path);
    }
    let mut locations = if cfg!(target_os = "macos") {
        vec![PathBuf::from("/Library/Java/JavaVirtualMachines")]
    } else if cfg!(windows) {
        vec![
            PathBuf::from("C:/Program Files/Eclipse Adoptium"),
            PathBuf::from("C:/Program Files/Java"),
        ]
    } else {
        vec![PathBuf::from("/usr/lib/jvm")]
    };
    if cfg!(target_os = "macos") {
        if let Some(home) = dirs::home_dir() {
            locations.push(home.join("Library/Java/JavaVirtualMachines"));
        }
        let homebrew =
            PathBuf::from("/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home");
        if is_java_21(&homebrew) {
            return Ok(homebrew);
        }
    }
    for location in locations {
        let entries = match fs::read_dir(&location) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("Could not inspect {}", location.display()));
            }
        };
        for entry in entries {
            let path = entry?.path();
            let path = if cfg!(target_os = "macos") {
                path.join("Contents/Home")
            } else {
                path
            };
            if is_java_21(&path) {
                return Ok(path);
            }
        }
    }
    bail!(
        "Kotlin compatibility setup requires JDK 21. Install it and set ANDROID_IDE_KOTLIN_JAVA_HOME to its home directory."
    )
}

fn is_java_21(path: &Path) -> bool {
    let java = if cfg!(windows) {
        "bin/java.exe"
    } else {
        "bin/java"
    };
    path.join(java).is_file()
        && fs::read_to_string(path.join("release")).is_ok_and(|release| {
            release
                .lines()
                .any(|line| line.starts_with("JAVA_VERSION=\"21.") || line == "JAVA_VERSION=\"21\"")
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[allow(
        clippy::disallowed_methods,
        reason = "This synchronous test executes the generated shell hook outside the UI executor"
    )]
    fn classpath_setup_preserves_user_hooks_and_handles_paths() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        let dependency = root.join("a dependency $literal.jar");
        fs::write(&dependency, "test")?;
        let output = format!(
            "noise\n{OUTPUT_PREFIX}{}\n",
            serde_json::to_string(&[&dependency, &dependency])?
        );
        let paths = parse_classpath(&output)?;
        assert_eq!(paths, vec![dependency]);
        assert_eq!(
            parse_sources(&format!(
                "{SOURCES_PREFIX}{}",
                serde_json::to_string(&paths)?
            ))?,
            paths
        );
        assert!(parse_sources(&format!("{SOURCES_PREFIX}[]"))?.is_empty());
        assert!(parse_sources(&format!("{SOURCES_PREFIX}[\"relative.jar\"]")).is_err());
        assert!(parse_classpath("no classpath").is_err());
        assert!(parse_classpath(&format!("{OUTPUT_PREFIX}[]")).is_err());
        assert!(parse_classpath(&format!("{OUTPUT_PREFIX}[\"relative.jar\"]")).is_err());
        assert!(parse_classpath(&(output.clone() + &output)).is_err());
        let (name, hook_contents) = hook();
        fs::write(root.join(name), "user hook")?;
        assert!(prepare(root).is_err());
        assert_eq!(fs::read_to_string(root.join(name))?, "user hook");
        fs::rename(root.join(name), root.join("user-hook-backup"))?;
        assert!(prepare(root)?.is_file());
        install_classpath(root, &paths)?;
        let previous = read_settings(root)?;
        finish(root, &paths, &previous, "{\"tab_size\": 2}\n")?;
        assert!(finish(root, &paths, &previous, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 2}\n");
        assert_eq!(fs::read_to_string(root.join(name))?, hook_contents);
        assert!(prepare(root)?.is_file());
        install_classpath(root, &paths)?;
        #[cfg(unix)]
        {
            let output = std::process::Command::new(root.join(name))
                .current_dir("/")
                .output()?;
            assert!(output.status.success());
            assert_eq!(
                String::from_utf8(output.stdout)?.trim(),
                paths
                    .first()
                    .context("missing path")?
                    .to_str()
                    .context("non-Unicode path")?
            );
        }
        Ok(())
    }
}
