use anyhow::{Context as _, Result, bail, ensure};
use std::{
    env, fs,
    io::Write,
    path::{Path, PathBuf},
};

pub const CLASSPATH_TASK: &str = "zedAndroidKotlinClasspath";
pub const RESOURCE_GENERATION_TASK: &str = "zedAndroidKotlinGenerateSources";
pub const OFFICIAL_VERSION: &str = "263.4702.0";
pub const OFFICIAL_REVISION: &str = "263.4702.0+android-3";
const OUTPUT_PREFIX: &str = "ZED_ANDROID_KOTLIN_CLASSPATH=";
const SOURCES_PREFIX: &str = "ZED_ANDROID_KOTLIN_SOURCES=";
const CACHE_MARKER: &str = "# Generated by Android IDE for Kotlin language support.\n*\n";
const UNIX_HOOK: &str = "#!/bin/sh\n# Generated by Android IDE for Kotlin language support.\ncat \"$(dirname \"$0\")/.zed/android-kotlin/classpath.txt\"\n";
const WINDOWS_HOOK: &str = "@echo off\r\nrem Generated by Android IDE for Kotlin language support.\r\ntype \"%~dp0.zed\\android-kotlin\\classpath.txt\"\r\n";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Backend {
    Community,
    Official,
}

impl Backend {
    pub fn from_environment() -> Result<Self> {
        match env::var("ANDROID_IDE_KOTLIN_BACKEND") {
            Ok(value) if value == "official" => Ok(Self::Official),
            Ok(value) if value == "community" => Ok(Self::Community),
            Err(env::VarError::NotPresent) => Ok(Self::Community),
            _ => bail!("ANDROID_IDE_KOTLIN_BACKEND must be official or community"),
        }
    }
}

// ponytail: one selected variant supplies the workspace classpath; replace with a per-module
// project model when mixed-variant or multiplatform editing is required.
const GRADLE_INIT: &str = r#"gradle.projectsEvaluated {
    allprojects { project ->
        def compile = project.tasks.findByName(System.getProperty('zed.android.compileTask'))
        if (compile != null && compile.hasProperty('libraries')) {
            def javaCompile = project.tasks.findByName(compile.name.replaceFirst(/Kotlin$/, 'JavaWithJavac'))
            def javaClasses = javaCompile == null ? project.files() :
                project.files(javaCompile.destinationDirectory).filter { it.isDirectory() }
            def variant = compile.name.replaceFirst(/^compile/, '').replaceFirst(/Kotlin$/, '')
            variant = variant.substring(0, 1).toLowerCase(java.util.Locale.ROOT) + variant.substring(1)
            def configuration = project.configurations.findByName(variant + 'CompileClasspath')
            def sources = []
            if (configuration != null) {
                def components = configuration.incoming.artifactView { view ->
                    view.componentFilter { it instanceof org.gradle.api.artifacts.component.ModuleComponentIdentifier }
                }.artifacts.artifacts.collect { it.id.componentIdentifier }.unique()
                def result = project.dependencies.createArtifactResolutionQuery().forComponents(components)
                    .withArtifacts(org.gradle.jvm.JvmLibrary, org.gradle.language.base.artifact.SourcesArtifact).execute()
                sources = result.resolvedComponents.collectMany { component ->
                    component.getArtifacts(org.gradle.language.base.artifact.SourcesArtifact)
                        .findAll { it instanceof org.gradle.api.artifacts.result.ResolvedArtifactResult }
                        .collect { it.file.absolutePath }
                }.unique().sort()
            }
            project.tasks.register('zedAndroidKotlinClasspath') {
                dependsOn(compile)
                if (javaCompile != null) { dependsOn(javaCompile) }
                // BuildConfig and other generated Java symbols are absent from compile.libraries.
                inputs.files(compile.libraries, javaClasses)
                inputs.property('androidSourceArchives', sources)
                doLast { task ->
                    println('ZED_ANDROID_KOTLIN_CLASSPATH=' + groovy.json.JsonOutput.toJson(
                        task.inputs.files.files.collect { it.absolutePath }))
                    println('ZED_ANDROID_KOTLIN_SOURCES=' + groovy.json.JsonOutput.toJson(
                        task.inputs.properties.androidSourceArchives))
                }
            }
        }
    }
}
"#;

pub fn server_binary() -> Result<Option<PathBuf>> {
    env::var_os("ANDROID_IDE_KOTLIN_SERVER")
        .map(|path| {
            let path = PathBuf::from(path);
            ensure!(
                path.is_absolute() && path.is_file(),
                "ANDROID_IDE_KOTLIN_SERVER must name an existing absolute server executable"
            );
            Ok(path)
        })
        .transpose()
}

pub fn official_server_binary() -> Result<PathBuf> {
    let path = env::var_os("ANDROID_IDE_OFFICIAL_KOTLIN_SERVER")
        .map(PathBuf::from)
        .context("Run script/install-android-kotlin --backend official and relaunch script/android-ide, or set ANDROID_IDE_OFFICIAL_KOTLIN_SERVER to its bin/intellij-server executable")?;
    validate_official_server(&path)?;
    Ok(path)
}

fn validate_official_server(path: &Path) -> Result<()> {
    ensure!(
        path.is_absolute() && path.is_file(),
        "ANDROID_IDE_OFFICIAL_KOTLIN_SERVER must name an existing absolute server executable"
    );
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        ensure!(
            fs::metadata(&path)?.permissions().mode() & 0o111 != 0,
            "The official Kotlin server must be executable"
        );
    }
    let installation = path
        .parent()
        .and_then(Path::parent)
        .context("The official Kotlin server must be inside its distribution's bin directory")?;
    let product: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(installation.join("product-info.json"))?)?;
    ensure!(
        product["buildNumber"] == OFFICIAL_VERSION,
        "Official Kotlin setup requires the tested release {OFFICIAL_VERSION}"
    );
    let importer: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(installation.join("zed-native-importer.json"))
            .context("Run script/install-android-kotlin --backend official for the Android native importer patch")?,
    )?;
    ensure!(
        importer["revision"] == OFFICIAL_REVISION,
        "Official Kotlin setup requires the tested Android importer {OFFICIAL_REVISION}"
    );
    Ok(())
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    validate_hooks(root)?;
    let cache = prepare_cache(root, "android-kotlin")?;
    let init = cache.join("classpath.gradle");
    atomic_write(&init, GRADLE_INIT, false)?;
    Ok(init)
}

fn prepare_cache(root: &Path, name: &str) -> Result<PathBuf> {
    let root = root.canonicalize()?;
    let settings = root.join(".zed");
    ensure_directory(&settings)?;
    let cache = settings.join(name);
    if cache.exists() {
        ensure!(
            !fs::symlink_metadata(&cache)?.file_type().is_symlink(),
            "Kotlin cache must not be a symlink"
        );
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
            "The {} directory already contains unmanaged files. Move it aside before configuring Kotlin.",
            cache.display()
        );
    } else {
        fs::create_dir(&cache)?;
        atomic_write(&cache.join(".gitignore"), CACHE_MARKER, false)?;
    }
    Ok(cache)
}

pub(crate) fn ensure_directory(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => ensure!(
            metadata.is_dir() && !metadata.file_type().is_symlink(),
            "{} must be a regular directory",
            path.display()
        ),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir(path)?,
        Err(error) => return Err(error.into()),
    }
    Ok(())
}

fn hook() -> (&'static str, &'static str) {
    if cfg!(windows) {
        ("kls-classpath.bat", WINDOWS_HOOK)
    } else {
        ("kls-classpath.sh", UNIX_HOOK)
    }
}

fn validate_hooks(root: &Path) -> Result<()> {
    let (name, expected) = hook();
    for candidate in [
        "kls-classpath",
        "kls-classpath.sh",
        "kls-classpath.bat",
        "kls-classpath.cmd",
    ] {
        let path = root.join(candidate);
        match fs::symlink_metadata(&path) {
            Ok(metadata) => ensure!(
                candidate == name
                    && metadata.is_file()
                    && !metadata.file_type().is_symlink()
                    && fs::read_to_string(&path)? == expected,
                "{} is an existing Kotlin classpath hook. It has been preserved; move it aside before using automatic setup.",
                path.display()
            ),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
    }
    Ok(())
}

pub fn parse_classpath(output: &str) -> Result<Vec<PathBuf>> {
    let paths = parse_paths(output, OUTPUT_PREFIX)?;
    ensure!(
        !paths.is_empty(),
        "The Kotlin compilation classpath is empty"
    );
    Ok(paths)
}

pub fn parse_sources(output: &str) -> Result<Vec<PathBuf>> {
    let paths = parse_paths(output, SOURCES_PREFIX)?;
    ensure!(
        paths.iter().all(|path| path.is_file()),
        "A Kotlin source archive is missing"
    );
    Ok(paths)
}

fn parse_paths(output: &str, prefix: &str) -> Result<Vec<PathBuf>> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(prefix));
    let record = records.next().context("Gradle did not return a Kotlin compilation classpath. This variant must have a Kotlin compile task.")?;
    ensure!(
        records.next().is_none(),
        "Gradle returned more than one Kotlin classpath"
    );
    let mut paths: Vec<PathBuf> =
        serde_json::from_str(record).context("Invalid Kotlin classpath output")?;
    for path in &paths {
        ensure!(
            path.is_absolute() && (path.is_file() || path.is_dir()),
            "Kotlin classpath entry is missing or not absolute: {}",
            path.display()
        );
        let text = path
            .to_str()
            .context("Kotlin classpath contains a non-Unicode path")?;
        let separator = if cfg!(windows) { ';' } else { ':' };
        ensure!(
            !text.contains(['\n', '\r', separator]),
            "Kotlin classpath contains an unsupported separator: {}",
            path.display()
        );
    }
    paths.sort();
    paths.dedup();
    Ok(paths)
}

pub fn install_classpath(root: &Path, paths: &[PathBuf]) -> Result<()> {
    ensure!(!paths.is_empty(), "The Kotlin classpath is empty");
    validate_hooks(root)?;
    let separator = if cfg!(windows) { ";" } else { ":" };
    let classpath = paths
        .iter()
        .map(|path| path.to_str().context("Non-Unicode Kotlin classpath"))
        .collect::<Result<Vec<_>>>()?
        .join(separator);
    let cache = root.join(".zed/android-kotlin");
    ensure!(
        fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
        "Prepare the Kotlin cache before installing its classpath"
    );
    atomic_write(&cache.join("classpath.txt"), &(classpath + "\n"), false)?;
    let (name, content) = hook();
    atomic_write(&root.join(name), content, true)
}

pub fn read_settings(root: &Path) -> Result<String> {
    let path = root.join(".zed/settings.json");
    match fs::symlink_metadata(&path) {
        Ok(metadata) => {
            ensure!(
                metadata.is_file() && !metadata.file_type().is_symlink(),
                "Project settings must be a regular file for automatic Kotlin setup"
            );
            fs::read_to_string(path).context("Could not read project settings")
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok("{}\n".into()),
        Err(error) => Err(error.into()),
    }
}

pub fn finish(
    root: &Path,
    paths: &[PathBuf],
    previous_settings: &str,
    updated_settings: &str,
) -> Result<()> {
    ensure!(
        read_settings(root)? == previous_settings,
        "Project settings changed during Kotlin setup. Retry to preserve your latest edits."
    );
    install_classpath(root, paths)?;
    atomic_write(&root.join(".zed/settings.json"), updated_settings, false)
}

const RESOURCE_GENERATION_GUARD: &str = r#"initscript {
    def server = System.getProperty('zed.android.kotlinServer')
    if (server == null) throw new GradleException('Missing official Kotlin server for Android resource generation')
    dependencies {
        classpath files(new File(server, 'plugins/kotlin.lsp/lib/modules/language-server.workspace-import.gradle-plugin.jar'),
            new File(server, 'plugins/kotlin/lib/intellij.libraries.kotlin.tooling.core.jar'))
    }
}
com.jetbrains.ls.imports.gradle.model.builder.android.AndroidVariants.collectAndroidVariants(gradle)
gradle.projectsEvaluated {
    // AGP's metadata writer reads artifact identities, not class contents. Its explicit
    // dependency builds those classes unnecessarily; transitive metadata inputs retain their dependencies.
    rootProject.allprojects.each { project ->
        project.tasks.configureEach { task ->
            def type = task.class
            while (type != null) {
                if (type.name == 'com.android.build.gradle.internal.tasks.featuresplit.PackagedDependenciesWriterTask') {
                    task.setDependsOn([])
                    break
                }
                type = type.superclass
            }
        }
    }
    rootProject.tasks.register('zedAndroidKotlinGenerateSources') {
        dependsOn(rootProject.allprojects.collectMany { project ->
            com.jetbrains.ls.imports.gradle.model.builder.android.AndroidUtilsKt.selectedAndroidGenerationTasks(project)
        })
    }
}
gradle.taskGraph.whenReady { graph ->
    def compilerTypes = [
        'org.gradle.api.tasks.compile.AbstractCompile',
        'org.gradle.api.tasks.compile.JavaCompile',
        'org.jetbrains.kotlin.gradle.tasks.KotlinCompile',
        'org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompile'
    ] as Set
    def compilers = graph.allTasks.findAll { task ->
        def pending = [task.class]
        def visited = [] as Set
        boolean compiler = false
        while (!pending.isEmpty()) {
            def type = pending.remove(pending.size() - 1)
            if (type != null && visited.add(type.name)) {
                if (compilerTypes.contains(type.name)) {
                    compiler = true
                    break
                }
                if (type.superclass != null) pending.add(type.superclass)
                pending.addAll(type.interfaces as List)
            }
        }
        compiler
    }.collect { it.path }.sort()
    if (!compilers.isEmpty()) {
        throw new GradleException('Android resource generation would compile project sources: ' + compilers.join(', ') + '. The resource task graph was not executed. Kotlin import can continue with generated symbols unavailable.')
    }
}
"#;

pub fn prepare_official_resource_generation(root: &Path) -> Result<PathBuf> {
    let cache = prepare_cache(root, "android-kotlin-official")?;
    let script = cache.join("resource-generation.gradle");
    atomic_write(&script, RESOURCE_GENERATION_GUARD, false)?;
    Ok(script)
}

pub fn finish_official(root: &Path, previous_settings: &str, updated_settings: &str) -> Result<()> {
    ensure!(
        read_settings(root)? == previous_settings,
        "Project settings changed during Kotlin setup. Retry to preserve your latest edits."
    );
    prepare_cache(root, "android-kotlin-official")?;
    atomic_write(&root.join(".zed/settings.json"), updated_settings, false)
}

pub(crate) fn atomic_write(path: &Path, text: &str, executable: bool) -> Result<()> {
    let parent = path
        .parent()
        .context("Generated file has no parent directory")?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(text.as_bytes())?;
    #[cfg(unix)]
    if executable {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(0o755))?;
    }
    #[cfg(not(unix))]
    let _executable = executable;
    temporary
        .persist(path)
        .with_context(|| format!("Could not write {}", path.display()))?;
    Ok(())
}

pub fn java_home() -> Result<PathBuf> {
    if let Some(path) = env::var_os("ANDROID_IDE_KOTLIN_JAVA_HOME") {
        let path = PathBuf::from(path);
        ensure!(
            is_java_21(&path),
            "ANDROID_IDE_KOTLIN_JAVA_HOME must point to JDK 21"
        );
        return Ok(path);
    }
    if let Some(path) = env::var_os("JAVA_HOME").map(PathBuf::from)
        && is_java_21(&path)
    {
        return Ok(path);
    }
    let mut locations = if cfg!(target_os = "macos") {
        vec![PathBuf::from("/Library/Java/JavaVirtualMachines")]
    } else if cfg!(windows) {
        vec![
            PathBuf::from("C:/Program Files/Eclipse Adoptium"),
            PathBuf::from("C:/Program Files/Java"),
        ]
    } else {
        vec![PathBuf::from("/usr/lib/jvm")]
    };
    if cfg!(target_os = "macos") {
        if let Some(home) = dirs::home_dir() {
            locations.push(home.join("Library/Java/JavaVirtualMachines"));
        }
        let homebrew =
            PathBuf::from("/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home");
        if is_java_21(&homebrew) {
            return Ok(homebrew);
        }
    }
    for location in locations {
        let entries = match fs::read_dir(&location) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("Could not inspect {}", location.display()));
            }
        };
        for entry in entries {
            let path = entry?.path();
            let path = if cfg!(target_os = "macos") {
                path.join("Contents/Home")
            } else {
                path
            };
            if is_java_21(&path) {
                return Ok(path);
            }
        }
    }
    bail!(
        "Kotlin compatibility setup requires JDK 21. Install it and set ANDROID_IDE_KOTLIN_JAVA_HOME to its home directory."
    )
}

fn is_java_21(path: &Path) -> bool {
    let java = if cfg!(windows) {
        "bin/java.exe"
    } else {
        "bin/java"
    };
    path.join(java).is_file()
        && fs::read_to_string(path.join("release")).is_ok_and(|release| {
            release
                .lines()
                .any(|line| line.starts_with("JAVA_VERSION=\"21.") || line == "JAVA_VERSION=\"21\"")
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn official_server_requires_the_tested_importer() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let server = directory.path().join("bin/intellij-server");
        fs::create_dir_all(server.parent().context("Missing bin directory")?)?;
        fs::write(&server, "#!/bin/sh\n")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&server, fs::Permissions::from_mode(0o755))?;
        }
        fs::write(
            directory.path().join("product-info.json"),
            serde_json::json!({"buildNumber": OFFICIAL_VERSION}).to_string(),
        )?;
        assert!(validate_official_server(&server).is_err());
        let marker = directory.path().join("zed-native-importer.json");
        fs::write(
            &marker,
            serde_json::json!({"revision": "unknown"}).to_string(),
        )?;
        assert!(validate_official_server(&server).is_err());
        fs::write(
            marker,
            serde_json::json!({"revision": OFFICIAL_REVISION}).to_string(),
        )?;
        validate_official_server(&server)?;
        Ok(())
    }

    #[test]
    fn official_resource_guard_uses_managed_cache() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let root = directory.path();
        let script = prepare_official_resource_generation(root)?;
        assert_eq!(fs::read_to_string(&script)?, RESOURCE_GENERATION_GUARD);
        fs::write(&script, "old generated guard")?;
        assert_eq!(prepare_official_resource_generation(root)?, script);
        assert_eq!(fs::read_to_string(&script)?, RESOURCE_GENERATION_GUARD);
        assert!(!root.join(".zed/settings.json").exists());
        fs::write(
            script
                .parent()
                .context("Guard cache missing")?
                .join(".gitignore"),
            "user content",
        )?;
        assert!(prepare_official_resource_generation(root).is_err());
        Ok(())
    }

    #[test]
    fn official_setup_needs_no_build_and_preserves_workspace_files() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        fs::write(root.join("Main.kt"), "fun broken( =")?;
        fs::write(root.join("kls-classpath.sh"), "user hook")?;
        let previous = read_settings(root)?;
        finish_official(root, &previous, "{\"tab_size\": 2}")?;
        assert_eq!(fs::read_to_string(root.join("Main.kt"))?, "fun broken( =");
        assert_eq!(
            fs::read_to_string(root.join("kls-classpath.sh"))?,
            "user hook"
        );
        assert_eq!(
            fs::read_to_string(root.join(".zed/android-kotlin-official/.gitignore"))?,
            CACHE_MARKER
        );
        assert!(!root.join(".zed/android-kotlin").exists());
        assert!(finish_official(root, &previous, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 2}");
        finish_official(root, &read_settings(root)?, "{\"tab_size\": 4}")?;
        fs::write(
            root.join(".zed/android-kotlin-official/.gitignore"),
            "unmanaged",
        )?;
        assert!(finish_official(root, &read_settings(root)?, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 4}");
        Ok(())
    }

    #[test]
    #[allow(
        clippy::disallowed_methods,
        reason = "This synchronous test executes the generated shell hook outside the UI executor"
    )]
    fn classpath_setup_preserves_user_hooks_and_handles_paths() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        let dependency = root.join("a dependency $literal.jar");
        fs::write(&dependency, "test")?;
        let output = format!(
            "noise\n{OUTPUT_PREFIX}{}\n",
            serde_json::to_string(&[&dependency, &dependency])?
        );
        let paths = parse_classpath(&output)?;
        assert_eq!(paths, vec![dependency]);
        assert_eq!(
            parse_sources(&format!(
                "{SOURCES_PREFIX}{}",
                serde_json::to_string(&paths)?
            ))?,
            paths
        );
        assert!(parse_sources(&format!("{SOURCES_PREFIX}[]"))?.is_empty());
        assert!(parse_sources(&format!("{SOURCES_PREFIX}[\"relative.jar\"]")).is_err());
        assert!(parse_classpath("no classpath").is_err());
        assert!(parse_classpath(&format!("{OUTPUT_PREFIX}[]")).is_err());
        assert!(parse_classpath(&format!("{OUTPUT_PREFIX}[\"relative.jar\"]")).is_err());
        assert!(parse_classpath(&(output.clone() + &output)).is_err());
        let (name, hook_contents) = hook();
        fs::write(root.join(name), "user hook")?;
        assert!(prepare(root).is_err());
        assert_eq!(fs::read_to_string(root.join(name))?, "user hook");
        fs::rename(root.join(name), root.join("user-hook-backup"))?;
        assert!(prepare(root)?.is_file());
        install_classpath(root, &paths)?;
        let previous = read_settings(root)?;
        finish(root, &paths, &previous, "{\"tab_size\": 2}\n")?;
        assert!(finish(root, &paths, &previous, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 2}\n");
        assert_eq!(fs::read_to_string(root.join(name))?, hook_contents);
        assert!(prepare(root)?.is_file());
        install_classpath(root, &paths)?;
        #[cfg(unix)]
        {
            let output = std::process::Command::new(root.join(name))
                .current_dir("/")
                .output()?;
            assert!(output.status.success());
            assert_eq!(
                String::from_utf8(output.stdout)?.trim(),
                paths
                    .first()
                    .context("missing path")?
                    .to_str()
                    .context("non-Unicode path")?
            );
        }
        Ok(())
    }
}
