use anyhow::{Context as _, Result, bail, ensure};
use std::{
    env, fs,
    io::Write,
    path::{Path, PathBuf},
};

pub const RESOURCE_GENERATION_TASK: &str = "zedAndroidKotlinGenerateSources";
pub const OFFICIAL_VERSION: &str = "263.4702.0";
pub const OFFICIAL_REVISION: &str = "263.4702.0+android-6";
const CACHE_MARKER: &str = "# Generated by Android IDE for Kotlin language support.\n*\n";

pub fn official_server_binary() -> Result<PathBuf> {
    let path = env::var_os("ANDROID_IDE_OFFICIAL_KOTLIN_SERVER")
        .map(PathBuf::from)
        .context("Run script/install-android-kotlin and relaunch script/android-ide, or set ANDROID_IDE_OFFICIAL_KOTLIN_SERVER to its bin/intellij-server executable")?;
    validate_official_server(&path)?;
    Ok(path)
}

fn validate_official_server(path: &Path) -> Result<()> {
    ensure!(
        path.is_absolute() && path.is_file(),
        "ANDROID_IDE_OFFICIAL_KOTLIN_SERVER must name an existing absolute server executable"
    );
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        ensure!(
            fs::metadata(&path)?.permissions().mode() & 0o111 != 0,
            "The official Kotlin server must be executable"
        );
    }
    let installation = path
        .parent()
        .and_then(Path::parent)
        .context("The official Kotlin server must be inside its distribution's bin directory")?;
    let product: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(installation.join("product-info.json"))?)?;
    ensure!(
        product["buildNumber"] == OFFICIAL_VERSION,
        "Official Kotlin setup requires the tested release {OFFICIAL_VERSION}"
    );
    let importer: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(installation.join("zed-native-importer.json"))
            .context("Run script/install-android-kotlin for the Android native importer patch")?,
    )?;
    ensure!(
        importer["revision"] == OFFICIAL_REVISION,
        "Official Kotlin setup requires the tested Android importer {OFFICIAL_REVISION}"
    );
    Ok(())
}

fn prepare_cache(root: &Path, name: &str) -> Result<PathBuf> {
    let root = root.canonicalize()?;
    let settings = root.join(".koda");
    ensure_directory(&settings)?;
    let cache = settings.join(name);
    if cache.exists() {
        ensure!(
            !fs::symlink_metadata(&cache)?.file_type().is_symlink(),
            "Kotlin cache must not be a symlink"
        );
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == CACHE_MARKER,
            "The {} directory already contains unmanaged files. Move it aside before configuring Kotlin.",
            cache.display()
        );
    } else {
        fs::create_dir(&cache)?;
        atomic_write(&cache.join(".gitignore"), CACHE_MARKER, false)?;
    }
    Ok(cache)
}

pub(crate) fn ensure_directory(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => ensure!(
            metadata.is_dir() && !metadata.file_type().is_symlink(),
            "{} must be a regular directory",
            path.display()
        ),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => fs::create_dir(path)?,
        Err(error) => return Err(error.into()),
    }
    Ok(())
}

pub fn read_settings(root: &Path) -> Result<String> {
    let path = root.join(".koda/settings.json");
    match fs::symlink_metadata(&path) {
        Ok(metadata) => {
            ensure!(
                metadata.is_file() && !metadata.file_type().is_symlink(),
                "Project settings must be a regular file for automatic Kotlin setup"
            );
            fs::read_to_string(path).context("Could not read project settings")
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok("{}\n".into()),
        Err(error) => Err(error.into()),
    }
}

const RESOURCE_GENERATION_GUARD: &str = r#"initscript {
    def server = System.getProperty('zed.android.kotlinServer')
    if (server == null) throw new GradleException('Missing official Kotlin server for Android resource generation')
    dependencies {
        classpath files(new File(server, 'plugins/kotlin.lsp/lib/modules/language-server.workspace-import.gradle-plugin.jar'),
            new File(server, 'plugins/kotlin/lib/intellij.libraries.kotlin.tooling.core.jar'))
    }
}
com.jetbrains.ls.imports.gradle.model.builder.android.AndroidVariants.collectAndroidVariants(gradle)
gradle.projectsEvaluated {
    // AGP's metadata writer reads artifact identities, not class contents. Its explicit
    // dependency builds those classes unnecessarily; transitive metadata inputs retain their dependencies.
    rootProject.allprojects.each { project ->
        project.tasks.configureEach { task ->
            def type = task.class
            while (type != null) {
                if (type.name == 'com.android.build.gradle.internal.tasks.featuresplit.PackagedDependenciesWriterTask') {
                    task.setDependsOn([])
                    break
                }
                type = type.superclass
            }
        }
    }
    rootProject.tasks.register('zedAndroidKotlinGenerateSources') {
        dependsOn(rootProject.allprojects.collectMany { project ->
            com.jetbrains.ls.imports.gradle.model.builder.android.AndroidUtilsKt.selectedAndroidGenerationTasks(project)
        })
    }
}
gradle.taskGraph.whenReady { graph ->
    def compilerTypes = [
        'org.gradle.api.tasks.compile.AbstractCompile',
        'org.gradle.api.tasks.compile.JavaCompile',
        'org.jetbrains.kotlin.gradle.tasks.KotlinCompile',
        'org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompile'
    ] as Set
    def compilers = graph.allTasks.findAll { task ->
        def pending = [task.class]
        def visited = [] as Set
        boolean compiler = false
        while (!pending.isEmpty()) {
            def type = pending.remove(pending.size() - 1)
            if (type != null && visited.add(type.name)) {
                if (compilerTypes.contains(type.name)) {
                    compiler = true
                    break
                }
                if (type.superclass != null) pending.add(type.superclass)
                pending.addAll(type.interfaces as List)
            }
        }
        compiler
    }.collect { it.path }.sort()
    if (!compilers.isEmpty()) {
        throw new GradleException('Android resource generation would compile project sources: ' + compilers.join(', ') + '. The resource task graph was not executed. Kotlin import can continue with generated symbols unavailable.')
    }
}
"#;

pub fn prepare_official_resource_generation(root: &Path) -> Result<PathBuf> {
    let cache = prepare_cache(root, "android-kotlin-official")?;
    let script = cache.join("resource-generation.gradle");
    atomic_write(&script, RESOURCE_GENERATION_GUARD, false)?;
    Ok(script)
}

pub fn finish_official(root: &Path, previous_settings: &str, updated_settings: &str) -> Result<()> {
    ensure!(
        read_settings(root)? == previous_settings,
        "Project settings changed during Kotlin setup. Retry to preserve your latest edits."
    );
    prepare_cache(root, "android-kotlin-official")?;
    atomic_write(&root.join(".koda/settings.json"), updated_settings, false)
}

pub(crate) fn atomic_write(path: &Path, text: &str, executable: bool) -> Result<()> {
    let parent = path
        .parent()
        .context("Generated file has no parent directory")?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(text.as_bytes())?;
    #[cfg(unix)]
    if executable {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(fs::Permissions::from_mode(0o755))?;
    }
    #[cfg(not(unix))]
    let _executable = executable;
    temporary
        .persist(path)
        .with_context(|| format!("Could not write {}", path.display()))?;
    Ok(())
}

pub fn java_home() -> Result<PathBuf> {
    java_home_from_environment(|variable| env::var_os(variable))
}

fn java_home_from_environment(
    mut environment: impl FnMut(&str) -> Option<std::ffi::OsString>,
) -> Result<PathBuf> {
    if let Some(path) = environment("ANDROID_IDE_KOTLIN_JAVA_HOME") {
        let path = PathBuf::from(path);
        ensure!(
            is_java_21(&path),
            "ANDROID_IDE_KOTLIN_JAVA_HOME must point to JDK 21"
        );
        return Ok(path);
    }
    if let Some(path) = environment("JAVA21_HOME") {
        let path = PathBuf::from(path);
        ensure!(is_java_21(&path), "JAVA21_HOME must point to JDK 21");
        return Ok(path);
    }
    if let Some(path) = environment("JAVA_HOME").map(PathBuf::from)
        && is_java_21(&path)
    {
        return Ok(path);
    }
    let mut locations = if cfg!(target_os = "macos") {
        vec![PathBuf::from("/Library/Java/JavaVirtualMachines")]
    } else if cfg!(windows) {
        vec![
            PathBuf::from("C:/Program Files/Eclipse Adoptium"),
            PathBuf::from("C:/Program Files/Java"),
        ]
    } else {
        vec![PathBuf::from("/usr/lib/jvm")]
    };
    if cfg!(target_os = "macos") {
        if let Some(home) = dirs::home_dir() {
            locations.push(home.join("Library/Java/JavaVirtualMachines"));
        }
        let homebrew =
            PathBuf::from("/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home");
        if is_java_21(&homebrew) {
            return Ok(homebrew);
        }
    }
    for location in locations {
        let entries = match fs::read_dir(&location) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => {
                return Err(error)
                    .with_context(|| format!("Could not inspect {}", location.display()));
            }
        };
        for entry in entries {
            let path = entry?.path();
            let path = if cfg!(target_os = "macos") {
                path.join("Contents/Home")
            } else {
                path
            };
            if is_java_21(&path) {
                return Ok(path);
            }
        }
    }
    bail!(
        "Kotlin compatibility setup requires JDK 21. Install it and set ANDROID_IDE_KOTLIN_JAVA_HOME to its home directory."
    )
}

fn is_java_21(path: &Path) -> bool {
    let java = if cfg!(windows) {
        "bin/java.exe"
    } else {
        "bin/java"
    };
    path.join(java).is_file()
        && fs::read_to_string(path.join("release")).is_ok_and(|release| {
            release
                .lines()
                .any(|line| line.starts_with("JAVA_VERSION=\"21.") || line == "JAVA_VERSION=\"21\"")
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn java_home_honors_the_installer_override_and_validates_explicit_jdks() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let java21 = temporary.path().join("custom jdk 21");
        let android21 = temporary.path().join("android jdk 21");
        let java25 = temporary.path().join("gradle jdk 25");
        for (path, version) in [(&java21, "21.0.9"), (&android21, "21.0.8"), (&java25, "25")] {
            fs::create_dir_all(path.join("bin"))?;
            fs::write(
                path.join(if cfg!(windows) {
                    "bin/java.exe"
                } else {
                    "bin/java"
                }),
                "",
            )?;
            fs::write(
                path.join("release"),
                format!("JAVA_VERSION=\"{version}\"\n"),
            )?;
        }
        let resolve = |android: Option<&Path>, installer: Option<&Path>, gradle: Option<&Path>| {
            java_home_from_environment(|variable| {
                match variable {
                    "ANDROID_IDE_KOTLIN_JAVA_HOME" => android,
                    "JAVA21_HOME" => installer,
                    "JAVA_HOME" => gradle,
                    _ => None,
                }
                .map(|path| path.as_os_str().to_owned())
            })
        };
        assert_eq!(resolve(None, Some(&java21), Some(&java25))?, java21);
        assert_eq!(
            resolve(Some(&android21), Some(&java21), Some(&java25))?,
            android21
        );
        assert_eq!(resolve(None, None, Some(&java21))?, java21);
        assert!(
            resolve(None, Some(&java25), Some(&java21))
                .expect_err("Invalid explicit JAVA21_HOME must not fall back")
                .to_string()
                .contains("JAVA21_HOME must point to JDK 21")
        );
        assert!(resolve(Some(&java25), Some(&java21), Some(&java21)).is_err());
        Ok(())
    }

    #[test]
    fn official_server_requires_the_tested_importer() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let server = directory.path().join("bin/intellij-server");
        fs::create_dir_all(server.parent().context("Missing bin directory")?)?;
        fs::write(&server, "#!/bin/sh\n")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&server, fs::Permissions::from_mode(0o755))?;
        }
        fs::write(
            directory.path().join("product-info.json"),
            serde_json::json!({"buildNumber": OFFICIAL_VERSION}).to_string(),
        )?;
        assert!(validate_official_server(&server).is_err());
        let marker = directory.path().join("zed-native-importer.json");
        fs::write(
            &marker,
            serde_json::json!({"revision": "unknown"}).to_string(),
        )?;
        assert!(validate_official_server(&server).is_err());
        fs::write(
            marker,
            serde_json::json!({"revision": OFFICIAL_REVISION}).to_string(),
        )?;
        validate_official_server(&server)?;
        Ok(())
    }

    #[test]
    fn official_resource_guard_uses_managed_cache() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let root = directory.path();
        let script = prepare_official_resource_generation(root)?;
        assert_eq!(fs::read_to_string(&script)?, RESOURCE_GENERATION_GUARD);
        fs::write(&script, "old generated guard")?;
        assert_eq!(prepare_official_resource_generation(root)?, script);
        assert_eq!(fs::read_to_string(&script)?, RESOURCE_GENERATION_GUARD);
        assert!(!root.join(".koda/settings.json").exists());
        fs::write(
            script
                .parent()
                .context("Guard cache missing")?
                .join(".gitignore"),
            "user content",
        )?;
        assert!(prepare_official_resource_generation(root).is_err());
        Ok(())
    }

    #[test]
    fn official_setup_needs_no_build_and_preserves_workspace_files() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        fs::write(root.join("Main.kt"), "fun broken( =")?;
        fs::write(root.join("kls-classpath.sh"), "user hook")?;
        let previous = read_settings(root)?;
        finish_official(root, &previous, "{\"tab_size\": 2}")?;
        assert_eq!(fs::read_to_string(root.join("Main.kt"))?, "fun broken( =");
        assert_eq!(
            fs::read_to_string(root.join("kls-classpath.sh"))?,
            "user hook"
        );
        assert_eq!(
            fs::read_to_string(root.join(".koda/android-kotlin-official/.gitignore"))?,
            CACHE_MARKER
        );
        assert!(!root.join(".koda/android-kotlin").exists());
        assert!(finish_official(root, &previous, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 2}");
        finish_official(root, &read_settings(root)?, "{\"tab_size\": 4}")?;
        fs::write(
            root.join(".koda/android-kotlin-official/.gitignore"),
            "unmanaged",
        )?;
        assert!(finish_official(root, &read_settings(root)?, "{}").is_err());
        assert_eq!(read_settings(root)?, "{\"tab_size\": 4}");
        Ok(())
    }
}
