use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    env, fs,
    path::{Component, Path, PathBuf},
};

pub const MODEL_TASK: &str = "zedAndroidPreviewModel";
const MARKER: &str = "# Generated by Android IDE for Compose preview.\n*\n";
const OUTPUT: &str = "ANDROID_IDE_PREVIEW_MODEL=";

// Gradle exposes the evaluated outputs; never guess AGP's version-specific intermediate directories.
const INIT: &str = r#"gradle.projectsEvaluated {
    def project = gradle.rootProject.project(System.getProperty('zed.android.module'))
    def variant = System.getProperty('zed.android.variant')
    def capitalized = variant.substring(0, 1).toUpperCase(java.util.Locale.ROOT) + variant.substring(1)
    def javaCompile = project.tasks.named('compile' + capitalized + 'JavaWithJavac')
    def kotlinCompile = project.tasks.named('compile' + capitalized + 'Kotlin')
    def resources = project.tasks.named('process' + capitalized + 'Resources')
    def runtime = project.configurations.getByName(variant + 'RuntimeClasspath').incoming.artifactView {
        attributes.attribute(org.gradle.api.artifacts.type.ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'android-classes-jar')
    }.files
    project.tasks.register('zedAndroidPreviewModel') {
        dependsOn(javaCompile, kotlinCompile, resources)
        inputs.files(runtime)
        doLast {
            def resourceClasses = resources.get().outputs.files.files.findAll { it.isFile() && it.name == 'R.jar' }
            if (resourceClasses.size() != 1) throw new GradleException('Expected one runtime R.jar from ' + resources.name)
            def classes = [kotlinCompile.get().destinationDirectory.get().asFile, javaCompile.get().destinationDirectory.get().asFile] + resourceClasses
            classes = classes.findAll { it.exists() }
            println('ANDROID_IDE_PREVIEW_MODEL=' + groovy.json.JsonOutput.toJson([
                module: project.path, variant: variant, namespace: project.android.namespace,
                classPath: (runtime.files + classes).unique()*.absolutePath,
                projectClassPath: classes*.absolutePath
            ]))
        }
    }
}
"#;

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub module: String,
    pub variant: String,
    pub namespace: String,
    pub class_path: Vec<PathBuf>,
    pub project_class_path: Vec<PathBuf>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Preview {
    #[serde(rename = "methodFQN")]
    pub method: String,
    #[serde(rename = "previewId")]
    pub id: String,
    #[serde(flatten)]
    pub parameters: serde_json::Map<String, Value>,
}

impl Preview {
    pub fn label(&self) -> String {
        let name = self
            .parameters
            .get("previewParams")
            .and_then(|parameters| parameters.get("name"))
            .and_then(Value::as_str)
            .filter(|name| !name.is_empty());
        match name {
            Some(name) => format!("{} · {name}", self.method),
            None => self.method.clone(),
        }
    }
}

pub fn installation() -> Result<PathBuf> {
    let directory = env::var_os("ANDROID_IDE_COMPOSE_PREVIEW").map(PathBuf::from)
        .context("Run script/install-android-preview, then relaunch script/android-ide to enable Compose preview.")?;
    ensure!(
        directory.is_absolute(),
        "ANDROID_IDE_COMPOSE_PREVIEW must be an absolute directory"
    );
    for file in [
        "PreviewBridge.class",
        "renderer.jar",
        "layoutlib.jar",
        "layoutlib/data/framework_res.jar",
    ] {
        ensure!(
            directory.join(file).is_file(),
            "Compose preview installation is incomplete: {file}"
        );
    }
    Ok(directory)
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    ensure_directory(&root.join(".zed"))?;
    let cache = root.join(".zed/android-preview");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == MARKER,
            "The .zed/android-preview directory contains unmanaged files. Move it aside before rendering previews."
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), MARKER, false)?;
    }
    atomic_write(&cache.join("export.gradle"), INIT, false)?;
    Ok(cache)
}

pub fn parse_model(output: &str, root: &Path, target: &AndroidTarget) -> Result<Model> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(OUTPUT));
    let model: Model = serde_json::from_str(
        records
            .next()
            .context("Gradle returned no Compose preview model")?,
    )?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Compose preview models"
    );
    ensure!(
        model.module == target.module && model.variant == target.variant,
        "The Compose model belongs to a different variant"
    );
    ensure!(
        !model.namespace.is_empty()
            && !model.class_path.is_empty()
            && !model.project_class_path.is_empty(),
        "The Compose model has no namespace or compiled classes"
    );
    let root = root.canonicalize()?;
    for path in &model.class_path {
        ensure!(
            path.is_absolute() && path.exists(),
            "Missing preview classpath entry: {}",
            path.display()
        );
    }
    for path in &model.project_class_path {
        ensure!(
            path.is_absolute()
                && path.canonicalize()?.starts_with(&root)
                && model.class_path.contains(path),
            "Preview project classes must belong to the selected project"
        );
    }
    Ok(model)
}

pub fn bridge_arguments(
    installation: &Path,
    operation: &str,
    input: &Path,
    output: Option<&Path>,
) -> Result<Vec<String>> {
    let classpath = env::join_paths([
        installation.to_path_buf(),
        installation.join("renderer.jar"),
        installation.join("layoutlib.jar"),
    ])?;
    let mut args = vec![
        "-Xmx2g".into(),
        "-Djava.awt.headless=true".into(),
        "--enable-native-access=ALL-UNNAMED".into(),
        "-cp".into(),
        classpath.to_string_lossy().into_owned(),
        "PreviewBridge".into(),
        operation.into(),
        input.to_string_lossy().into_owned(),
    ];
    if let Some(output) = output {
        args.push(output.to_string_lossy().into_owned());
    }
    Ok(args)
}

pub fn read_previews(path: &Path) -> Result<Vec<Preview>> {
    let previews: Vec<Preview> = serde_json::from_str(&fs::read_to_string(path)?)?;
    ensure!(
        !previews.is_empty(),
        "No Compose @Preview methods were found in this application module. Add @Preview to a composable and rebuild."
    );
    for preview in &previews {
        ensure!(
            !preview.id.is_empty() && !preview.method.is_empty(),
            "Preview discovery returned an invalid method"
        );
    }
    Ok(previews)
}

pub fn render_settings(
    model: &Model,
    preview: &Preview,
    apk: &Path,
    installation: &Path,
    output: &Path,
) -> Value {
    json!({"namespace": model.namespace, "classPath": model.class_path, "projectClassPath": model.project_class_path,
        "layoutlibPath": installation.join("layoutlib"), "resourceApkPath": apk,
        "outputFolder": output, "metaDataFolder": output.join("metadata"), "resultsFilePath": output.join("results.json"), "screenshots": [preview]})
}

fn render_failure(error: &Value) -> String {
    error
        .as_str()
        .or_else(|| {
            error
                .get("message")
                .and_then(Value::as_str)
                .filter(|message| !message.is_empty())
        })
        .or_else(|| error.get("stackTrace").and_then(Value::as_str))
        .map(|message| message.lines().take(8).collect::<Vec<_>>().join("\n"))
        .unwrap_or_else(|| error.to_string())
}

pub fn rendered_image(output: &Path) -> Result<PathBuf> {
    let results: Value = serde_json::from_str(
        &fs::read_to_string(output.join("results.json"))
            .context("The Compose renderer returned no result")?,
    )?;
    ensure!(
        results["globalError"].is_null(),
        "Compose rendering failed: {}",
        render_failure(&results["globalError"])
    );
    let screenshots = results["screenshotResults"]
        .as_array()
        .context("Invalid Compose rendering result")?;
    ensure!(
        !screenshots.is_empty(),
        "The Compose renderer produced no images"
    );
    let mut images = Vec::new();
    for screenshot in screenshots {
        ensure!(
            screenshot["error"].is_null(),
            "Compose preview failed: {}",
            render_failure(&screenshot["error"])
        );
        let relative = Path::new(
            screenshot["imagePath"]
                .as_str()
                .context("The preview has no image path")?,
        );
        ensure!(
            !relative.as_os_str().is_empty()
                && relative
                    .components()
                    .all(|part| matches!(part, Component::Normal(_))),
            "Preview image must stay inside its output directory"
        );
        let image = output.join(relative).canonicalize()?;
        ensure!(
            image.starts_with(output.canonicalize()?)
                && image.is_file()
                && image
                    .extension()
                    .is_some_and(|extension| extension == "png"),
            "Invalid Compose preview image"
        );
        images.push(image);
    }
    // ponytail: display one image per preview; add a gallery before exposing multi-value PreviewParameter providers.
    ensure!(
        images.len() == 1,
        "This preview generated multiple parameter values. A preview gallery is not supported yet; select a single-value preview."
    );
    images
        .into_iter()
        .next()
        .context("No Compose preview image")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_preview_model_results_and_owned_cache() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        let cache = prepare(root)?;
        assert_eq!(prepare(root)?, cache);
        let classes = root.join("classes");
        fs::create_dir(&classes)?;
        let target = AndroidTarget {
            module: ":mobile".into(),
            variant: "demoDebug".into(),
            output_listing: root.join("metadata.json"),
        };
        let model = json!({"module": ":mobile", "variant":"demoDebug", "namespace":"dev.sample", "classPath":[classes], "projectClassPath":[classes]});
        let record = format!("{OUTPUT}{model}");
        assert_eq!(parse_model(&record, root, &target)?.variant, "demoDebug");
        assert!(parse_model(&format!("{record}\n{record}"), root, &target).is_err());
        let mut wrong = model;
        wrong["variant"] = "fullDebug".into();
        assert!(parse_model(&format!("{OUTPUT}{wrong}"), root, &target).is_err());
        let output = root.join("output");
        fs::create_dir(&output)?;
        fs::write(output.join("sample.png"), b"PNG fixture")?;
        assert_eq!(
            render_failure(&json!({"message":"Preview failure", "stackTrace":"Long stack"})),
            "Preview failure"
        );
        let results = output.join("results.json");
        fs::write(
            &results,
            r#"{"screenshotResults":[{"imagePath":"sample.png"}]}"#,
        )?;
        assert_eq!(
            rendered_image(&output)?,
            output.join("sample.png").canonicalize()?
        );
        for invalid in [
            r#"{"globalError":"failed"}"#,
            r#"{"screenshotResults":[]}"#,
            r#"{"screenshotResults":[{"imagePath":"../outside.png"}]}"#,
            r#"{"screenshotResults":[{"imagePath":"sample.png","error":{"message":"render failed"}}]}"#,
        ] {
            fs::write(&results, invalid)?;
            assert!(rendered_image(&output).is_err());
        }
        fs::write(cache.join(".gitignore"), "User files")?;
        assert!(prepare(root).is_err());
        Ok(())
    }
}
