use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Component as PathComponent, Path, PathBuf},
    sync::Arc,
};

pub const MODEL_TASK: &str = "kodaAndroidProjectModel";
const OUTPUT: &str = "KODA_ANDROID_PROJECT_MODEL=";
const MARKER: &str = "# Generated by Koda for Android project models.\n*\n";
const EXPORT: &str = include_str!("project_model.gradle");

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Deserialize, Serialize)]
pub struct VariantId {
    pub module: String,
    pub variant: String,
}

impl From<&AndroidTarget> for VariantId {
    fn from(target: &AndroidTarget) -> Self {
        Self {
            module: target.module.clone(),
            variant: target.variant.clone(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ModuleKind {
    Application,
    Library,
    DynamicFeature,
    Test,
    Jvm,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceScope {
    Main,
    UnitTest,
    AndroidTest,
    TestFixtures,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceKind {
    Java,
    Kotlin,
    Resources,
    Manifest,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceRoot {
    pub path: PathBuf,
    pub kind: SourceKind,
    pub generated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum Dependency {
    Project { module: String, variant: String },
    External { coordinate: String },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Component {
    pub name: String,
    #[serde(default)]
    pub namespace: Option<String>,
    pub scope: SourceScope,
    pub sources: Vec<SourceRoot>,
    pub dependencies: Vec<Dependency>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Variant {
    pub name: String,
    pub components: Vec<Component>,
    pub output_listing: Option<PathBuf>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Module {
    pub path: String,
    pub directory: PathBuf,
    pub namespace: Option<String>,
    pub kind: ModuleKind,
    pub variants: Vec<Variant>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectModel {
    pub version: u32,
    pub root: PathBuf,
    pub modules: Vec<Module>,
    pub diagnostics: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct SelectedProject {
    pub model: Arc<ProjectModel>,
    pub selected: VariantId,
    pub variants: BTreeMap<String, String>,
}

impl ProjectModel {
    pub fn targets(&self) -> Vec<AndroidTarget> {
        let mut targets = self
            .modules
            .iter()
            .filter(|module| module.kind == ModuleKind::Application)
            .flat_map(|module| {
                module.variants.iter().filter_map(|variant| {
                    Some(AndroidTarget {
                        module: module.path.clone(),
                        variant: variant.name.clone(),
                        output_listing: variant.output_listing.clone()?,
                    })
                })
            })
            .collect::<Vec<_>>();
        targets.sort_by(|left, right| {
            (&left.module, &left.variant).cmp(&(&right.module, &right.variant))
        });
        targets
    }

    pub fn variant(&self, id: &VariantId) -> Option<(&Module, &Variant)> {
        let module = self
            .modules
            .iter()
            .find(|module| module.path == id.module)?;
        Some((
            module,
            module
                .variants
                .iter()
                .find(|variant| variant.name == id.variant)?,
        ))
    }

    pub fn select(self: &Arc<Self>, selected: VariantId) -> Result<SelectedProject> {
        let mut variants = BTreeMap::new();
        let mut pending = vec![selected.clone()];
        while let Some(id) = pending.pop() {
            if let Some(previous) = variants.insert(id.module.clone(), id.variant.clone()) {
                ensure!(
                    previous == id.variant,
                    "The selected graph requires multiple variants of {} ({previous}, {}); one active variant cannot represent it",
                    id.module,
                    id.variant
                );
                continue;
            }
            let (_, variant) = self.variant(&id).with_context(|| {
                format!(
                    "Android variant {} in {} is unavailable; sync again",
                    id.variant, id.module
                )
            })?;
            for component in &variant.components {
                for dependency in &component.dependencies {
                    if let Dependency::Project { module, variant } = dependency {
                        pending.push(VariantId {
                            module: module.clone(),
                            variant: variant.clone(),
                        });
                    }
                }
            }
        }
        Ok(SelectedProject {
            model: self.clone(),
            selected,
            variants,
        })
    }
}

impl SelectedProject {
    /// Modules visible to a source component. Test-only edges do not enter a main source scope.
    pub fn visible_modules(&self, owner: &str, scope: SourceScope) -> BTreeSet<String> {
        let mut visible = BTreeSet::new();
        let mut pending = vec![owner.to_owned()];
        while let Some(path) = pending.pop() {
            if !visible.insert(path.clone()) {
                continue;
            }
            let Some((module, variant)) = self.modules().find(|(module, _)| module.path == path)
            else {
                continue;
            };
            for component in &variant.components {
                if component.scope != SourceScope::Main
                    && !(path == owner && component.scope == scope)
                {
                    continue;
                }
                pending.extend(component.dependencies.iter().filter_map(|dependency| {
                    if let Dependency::Project {
                        module: dependency, ..
                    } = dependency
                    {
                        // Features belong to the app package but are not visible to base app sources.
                        let packaged_feature = module.kind == ModuleKind::Application
                            && self.modules().any(|(candidate, _)| {
                                candidate.path == *dependency
                                    && candidate.kind == ModuleKind::DynamicFeature
                            });
                        (!packaged_feature).then(|| dependency.clone())
                    } else {
                        None
                    }
                }));
            }
        }
        visible
    }

    pub fn modules(&self) -> impl Iterator<Item = (&Module, &Variant)> {
        self.variants.iter().filter_map(|(module, variant)| {
            self.model.variant(&VariantId {
                module: module.clone(),
                variant: variant.clone(),
            })
        })
    }

    pub fn projection(&self) -> serde_json::Value {
        serde_json::Value::Array(self.modules().map(|(module, variant)| serde_json::json!({
            "project": module.path, "variant": variant.name, "directory": module.directory,
            "kind": module.kind, "components": variant.components,
        })).collect())
    }

    pub fn kotlin_variants(&self) -> String {
        self.variants
            .iter()
            .filter(|(module, _)| {
                self.model.modules.iter().any(|candidate| {
                    candidate.path == **module && candidate.kind != ModuleKind::Jvm
                })
            })
            .map(|(module, variant)| format!("{module}={variant}"))
            .collect::<Vec<_>>()
            .join(";")
    }

    pub fn validate_target(&self, target: &AndroidTarget) -> Result<()> {
        ensure!(
            self.selected == VariantId::from(target) && self.model.targets().contains(target),
            "The Android target does not belong to the current project model"
        );
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ModelToken {
    generation: u64,
    root: Option<PathBuf>,
}

#[derive(Default)]
pub struct ModelState {
    generation: u64,
    root: Option<PathBuf>,
    pub model: Option<Arc<ProjectModel>>,
    pub selected: Option<Arc<SelectedProject>>,
}

impl ModelState {
    pub fn root(&self) -> Option<&Path> {
        self.root.as_deref()
    }

    pub fn token(&self) -> ModelToken {
        ModelToken {
            generation: self.generation,
            root: self.root.clone(),
        }
    }
    pub fn is_current(&self, token: &ModelToken) -> bool {
        self.token() == *token
    }
    pub fn invalidate(&mut self, root: Option<PathBuf>) -> ModelToken {
        self.generation = self.generation.wrapping_add(1);
        self.root = root;
        self.model = None;
        self.selected = None;
        self.token()
    }
    pub fn publish(&mut self, token: &ModelToken, model: ProjectModel) -> Result<()> {
        ensure!(
            self.is_current(token)
                && self.root.as_ref().is_some_and(|root| root == &model.root
                    || root.canonicalize().is_ok_and(|root| root == model.root)),
            "Discarded an outdated Android sync result"
        );
        self.model = Some(Arc::new(model));
        Ok(())
    }
    pub fn select(&mut self, id: Option<VariantId>) -> Result<()> {
        self.generation = self.generation.wrapping_add(1);
        self.selected = None;
        if let Some(id) = id {
            self.selected = Some(Arc::new(
                self.model
                    .as_ref()
                    .context("Sync the Android project first")?
                    .select(id)?,
            ));
        }
        Ok(())
    }
}

fn valid_module(name: &str) -> bool {
    name == ":"
        || (name.starts_with(':')
            && name[1..].split(':').all(|part| {
                !part.is_empty()
                    && part.chars().all(|character| {
                        character.is_ascii_alphanumeric() || "_-.$".contains(character)
                    })
            }))
}
fn valid_variant(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_-".contains(character))
}

pub fn parse_model(output: &str, root: &Path) -> Result<ProjectModel> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(OUTPUT));
    let model: ProjectModel = serde_json::from_str(
        records
            .next()
            .context("Gradle returned no Android project model")?,
    )?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Android project models"
    );
    ensure!(
        model.version == 1,
        "Unsupported Android project model version {}",
        model.version
    );
    let root = root.canonicalize()?;
    ensure!(
        model.root == root,
        "The Android model belongs to a different project"
    );
    let mut modules = BTreeSet::new();
    for module in &model.modules {
        ensure!(
            valid_module(&module.path) && modules.insert(&module.path),
            "Invalid or duplicate Android module {}",
            module.path
        );
        ensure!(
            module.directory.is_absolute() && module.directory.canonicalize()?.starts_with(&root),
            "Module {} is outside the selected build; included builds and external project directories are unsupported",
            module.path
        );
        let mut variants = BTreeSet::new();
        for variant in &module.variants {
            ensure!(
                valid_variant(&variant.name) && variants.insert(&variant.name),
                "Invalid or duplicate Android variant {}",
                variant.name
            );
            ensure!(
                variant
                    .components
                    .iter()
                    .filter(|component| component.scope == SourceScope::Main)
                    .count()
                    == 1,
                "Android variant {} must contain exactly one main component",
                variant.name
            );
            let mut components = BTreeSet::new();
            for component in &variant.components {
                ensure!(
                    valid_variant(&component.name) && components.insert(&component.name),
                    "Invalid or duplicate Android component {}",
                    component.name
                );
                for source in &component.sources {
                    validate_project_path(&source.path, &root)?;
                }
                for dependency in &component.dependencies {
                    if let Dependency::Project { module, variant } = dependency {
                        ensure!(
                            model
                                .variant(&VariantId {
                                    module: module.clone(),
                                    variant: variant.clone()
                                })
                                .is_some(),
                            "Dependency {module}:{variant} is absent from the Android project model"
                        );
                    }
                }
            }
            if let Some(path) = &variant.output_listing {
                validate_project_path(path, &root)?;
            }
        }
    }
    ensure!(
        model
            .modules
            .iter()
            .any(|module| module.kind != ModuleKind::Jvm),
        "No supported Android modules were found"
    );
    Ok(model)
}

fn validate_project_path(path: &Path, root: &Path) -> Result<()> {
    ensure!(
        path.is_absolute()
            && path.starts_with(root)
            && !path
                .components()
                .any(|part| matches!(part, PathComponent::ParentDir)),
        "Android model path is outside the selected project: {}",
        path.display()
    );
    // Generated roots may not exist until their producer has run. Resolve the nearest
    // existing ancestor so missing paths cannot bypass the symlink boundary check.
    let ancestor = path
        .ancestors()
        .find(|ancestor| ancestor.exists())
        .context("Android model path has no existing ancestor")?;
    ensure!(
        ancestor.canonicalize()?.starts_with(root),
        "Android model path escapes the project through a symlink: {}",
        path.display()
    );
    Ok(())
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    ensure_directory(&root.join(".koda"))?;
    let cache = root.join(".koda/android-model");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == MARKER,
            "The .koda/android-model directory contains unmanaged files; move it aside before syncing"
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), MARKER, false)?;
    }
    let script = cache.join("export.gradle");
    atomic_write(&script, EXPORT, false)?;
    Ok(script)
}

pub fn install_selection(root: &Path, selected: &SelectedProject) -> Result<PathBuf> {
    ensure!(
        selected.model.root == root.canonicalize()?,
        "The Android selection belongs to a different project"
    );
    let cache = prepare(root)?
        .parent()
        .context("Android model cache has no parent")?
        .to_path_buf();
    let path = cache.join("selected.json");
    atomic_write(
        &path,
        &serde_json::to_string(&selected.projection())?,
        false,
    )?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn component(
        name: &str,
        scope: SourceScope,
        dependencies: Vec<Dependency>,
        sources: Vec<SourceRoot>,
    ) -> Component {
        Component {
            name: name.into(),
            namespace: None,
            scope,
            dependencies,
            sources,
        }
    }
    fn variant(name: &str, dependencies: Vec<Dependency>) -> Variant {
        Variant {
            name: name.into(),
            output_listing: None,
            components: vec![component(name, SourceScope::Main, dependencies, Vec::new())],
        }
    }
    fn dependency(module: &str, variant: &str) -> Dependency {
        Dependency::Project {
            module: module.into(),
            variant: variant.into(),
        }
    }

    fn fixture(root: &Path) -> Result<ProjectModel> {
        for module in ["app", "library", "feature", "testing"] {
            fs::create_dir_all(root.join(module))?;
        }
        let mut application = variant(
            "paidDebug",
            vec![
                dependency(":library", "freeRelease"),
                dependency(":feature", "paidDebug"),
            ],
        );
        application.output_listing =
            Some(root.join("app/build/outputs/apk/paid/debug/output-metadata.json"));
        application.components[0].sources = vec![
            SourceRoot {
                path: root.join("app/src/main/java"),
                kind: SourceKind::Java,
                generated: false,
            },
            SourceRoot {
                path: root.join("app/src/paid/kotlin"),
                kind: SourceKind::Kotlin,
                generated: false,
            },
            SourceRoot {
                path: root.join("app/build/generated/ksp/paidDebug/kotlin"),
                kind: SourceKind::Kotlin,
                generated: true,
            },
            SourceRoot {
                path: root.join("app/src/paid/res"),
                kind: SourceKind::Resources,
                generated: false,
            },
        ];
        application.components.push(component(
            "paidDebugUnitTest",
            SourceScope::UnitTest,
            vec![
                dependency(":testing", "jvm"),
                Dependency::External {
                    coordinate: "junit:junit:4.13.2".into(),
                },
            ],
            vec![SourceRoot {
                path: root.join("app/src/test/java"),
                kind: SourceKind::Java,
                generated: false,
            }],
        ));
        application.components.push(component(
            "paidDebugAndroidTest",
            SourceScope::AndroidTest,
            vec![],
            vec![],
        ));
        application.components.push(component(
            "paidDebugTestFixtures",
            SourceScope::TestFixtures,
            vec![],
            vec![],
        ));
        let module = |name: &str, kind, variants| Module {
            path: format!(":{name}"),
            directory: root.join(name),
            namespace: Some(format!("dev.{name}")),
            kind,
            variants,
        };
        Ok(ProjectModel {
            version: 1,
            root: root.to_path_buf(),
            diagnostics: Vec::new(),
            modules: vec![
                module(
                    "app",
                    ModuleKind::Application,
                    vec![application, variant("freeDebug", vec![])],
                ),
                module(
                    "library",
                    ModuleKind::Library,
                    vec![variant("freeRelease", vec![]), variant("freeDebug", vec![])],
                ),
                module(
                    "feature",
                    ModuleKind::DynamicFeature,
                    vec![variant("paidDebug", vec![dependency(":app", "paidDebug")])],
                ),
                module("testing", ModuleKind::Jvm, vec![variant("jvm", vec![])]),
            ],
        })
    }
    fn output(model: &ProjectModel) -> Result<String> {
        Ok(format!(
            "Gradle noise\n{OUTPUT}{}\nBUILD SUCCESSFUL",
            serde_json::to_string(model)?
        ))
    }

    #[test]
    fn flavor_fallbacks_tests_dynamic_features_and_missing_generated_roots() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let model = Arc::new(parse_model(&output(&fixture(&root)?)?, &root)?);
        let target = model
            .targets()
            .into_iter()
            .next()
            .context("Expected an application target")?;
        assert_eq!(target.module, ":app");
        assert_eq!(target.variant, "paidDebug");
        let selected = model.select(VariantId::from(&target))?;
        assert_eq!(
            selected.variants.get(":library").map(String::as_str),
            Some("freeRelease")
        );
        assert_eq!(
            selected.variants.get(":testing").map(String::as_str),
            Some("jvm")
        );
        assert_eq!(
            selected.kotlin_variants(),
            ":app=paidDebug;:feature=paidDebug;:library=freeRelease"
        );
        assert_eq!(selected.modules().count(), 4);
        assert!(
            !selected
                .visible_modules(":app", SourceScope::Main)
                .contains(":testing")
        );
        assert!(
            selected
                .visible_modules(":app", SourceScope::UnitTest)
                .contains(":testing")
        );
        assert!(
            !selected
                .visible_modules(":app", SourceScope::AndroidTest)
                .contains(":testing")
        );
        assert!(
            !selected
                .visible_modules(":app", SourceScope::Main)
                .contains(":feature")
        );
        assert!(
            selected
                .visible_modules(":feature", SourceScope::Main)
                .contains(":app")
        );
        selected.validate_target(&target)?;
        assert!(
            selected
                .validate_target(&AndroidTarget {
                    variant: "freeDebug".into(),
                    ..target
                })
                .is_err()
        );
        let (_, variant) = model
            .variant(&selected.selected)
            .context("Expected the selected variant")?;
        assert_eq!(variant.components.len(), 4);
        assert!(
            variant.components[0]
                .sources
                .iter()
                .any(|source| source.generated && !source.path.exists())
        );
        assert!(!variant.components[0].dependencies.iter().any(|dependency| matches!(dependency, Dependency::External { coordinate } if coordinate.contains("junit"))));
        Ok(())
    }

    #[test]
    fn rejects_conflicting_test_dependency_variants_and_removed_variants() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        model.modules[0].variants[0].components[1]
            .dependencies
            .push(dependency(":library", "freeDebug"));
        let model = Arc::new(parse_model(&output(&model)?, &root)?);
        let error = model
            .select(VariantId {
                module: ":app".into(),
                variant: "paidDebug".into(),
            })
            .expect_err("Conflicting main/test library variants should fail");
        assert!(error.to_string().contains("multiple variants"));
        assert!(
            model
                .select(VariantId {
                    module: ":app".into(),
                    variant: "removedDebug".into()
                })
                .is_err()
        );
        Ok(())
    }

    #[test]
    fn rejects_outdated_sync_variant_aba_failed_sync_and_project_aba() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut state = ModelState::default();
        let first_sync = state.invalidate(Some(root.clone()));
        state.publish(&first_sync, fixture(&root)?)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        let first_variant = state.token();
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "freeDebug".into(),
        }))?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        assert!(!state.is_current(&first_variant));
        let failed_sync = state.invalidate(Some(root.clone()));
        assert!(state.model.is_none() && state.selected.is_none());
        assert!(state.publish(&first_sync, fixture(&root)?).is_err());
        let recovery = state.invalidate(Some(root.clone()));
        assert!(state.publish(&failed_sync, fixture(&root)?).is_err());
        state.publish(&recovery, fixture(&root)?)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        let old_project = state.token();
        state.invalidate(None);
        state.invalidate(Some(root));
        assert!(!state.is_current(&old_project));
        Ok(())
    }

    #[test]
    fn validates_model_schema_duplicate_records_paths_and_owned_cache() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let record = output(&model)?;
        assert!(parse_model(&(record.clone() + "\n" + &record), &root).is_err());
        model.version = 2;
        assert!(parse_model(&output(&model)?, &root).is_err());
        model.version = 1;
        model.modules.push(model.modules[0].clone());
        assert!(parse_model(&output(&model)?, &root).is_err());
        model.modules.pop();
        model.modules[0].variants[0].components[0].sources[0].path = root.join("../escape/missing");
        assert!(parse_model(&output(&model)?, &root).is_err());
        #[cfg(unix)]
        {
            let outside = tempfile::tempdir()?;
            std::os::unix::fs::symlink(outside.path(), root.join("escaped"))?;
            model.modules[0].variants[0].components[0].sources[0].path =
                root.join("escaped/not-created");
            assert!(parse_model(&output(&model)?, &root).is_err());
        }
        let cache = root.join(".koda/android-model");
        fs::create_dir_all(&cache)?;
        fs::write(cache.join(".gitignore"), "user files")?;
        assert!(prepare(&root).is_err());
        assert_eq!(fs::read_to_string(cache.join(".gitignore"))?, "user files");
        fs::rename(&cache, root.join("user-cache"))?;
        assert!(prepare(&root)?.is_file());
        assert!(prepare(&root)?.is_file());
        Ok(())
    }

    #[test]
    fn java_and_preview_adapters_use_the_selected_graph_and_component_scopes() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let model = Arc::new(fixture(&root)?);
        let selected = model.select(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        })?;
        let (_, selection) = crate::java::prepare_selected(&root, &selected)?;
        let projection: serde_json::Value = serde_json::from_str(&fs::read_to_string(selection)?)?;
        let components = projection[0]["components"]
            .as_array()
            .context("Missing components")?;
        assert_eq!(components.len(), 4);
        assert_eq!(components[1]["scope"], "unitTest");
        let java_modules = selected
            .modules()
            .map(|(module, variant)| crate::java::JavaModule {
                project: module.path.clone(),
                variant: variant.name.clone(),
                directory: module.directory.clone(),
                source_compatibility: "11".into(),
                target_compatibility: "11".into(),
                sources: vec![],
                libraries: vec![],
                test_sources: vec![],
                test_libraries: vec![],
            })
            .collect::<Vec<_>>();
        crate::java::validate_selection(&java_modules, &selected)?;
        assert!(crate::java::validate_selection(&java_modules[1..], &selected).is_err());
        let mut wrong_java = java_modules;
        wrong_java[0]
            .test_sources
            .push(root.join("app/src/free/java"));
        assert!(crate::java::validate_selection(&wrong_java, &selected).is_err());
        let mut preview = crate::preview::Model {
            module: ":app".into(),
            variant: "paidDebug".into(),
            namespace: "dev.app".into(),
            class_path: vec![],
            project_class_path: vec![],
        };
        crate::preview::validate_selection(&preview, &selected)?;
        preview.namespace = "dev.previous".into();
        assert!(crate::preview::validate_selection(&preview, &selected).is_err());
        Ok(())
    }
    #[cfg(unix)]
    #[test]
    fn publish_model_for_a_symlink_opened_root() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let alias = root.join("project-alias");
        let project = root.join("project");
        fs::create_dir(&project)?;
        std::os::unix::fs::symlink(&project, &alias)?;
        let mut state = ModelState::default();
        let token = state.invalidate(Some(alias));
        let model = fixture(&project)?;
        state.publish(&token, model)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        assert!(state.selected.is_some());
        Ok(())
    }
}
